// Code generated by forj generate --storage. DO NOT EDIT.
// Run: forj generate --storage
package storages

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/goforj/env/v2"
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
	"github.com/goforj/str"
)

const defaultDiskName storage.DiskName = "default"

const (
	driverDropbox = "dropbox"
	driverFTP     = "ftp"
	driverGCS     = "gcs"
	driverLocal   = "local"
	driverMemory  = "memory"
	driverRclone  = "rclone"
	driverRedis   = "redis"
	driverS3      = "s3"
	driverSFTP    = "sftp"
)

var storageRootKeys = []string{
	"DRIVER",
	"ROOT",
	"PREFIX",
	"ADDR",
	"USERNAME",
	"PASSWORD",
	"DB",
	"HOST",
	"PORT",
	"USER",
	"TLS",
	"INSECURE_SKIP_VERIFY",
	"KEY_PATH",
	"KNOWN_HOSTS_PATH",
	"INSECURE_IGNORE_HOST_KEY",
	"BUCKET",
	"ENDPOINT",
	"REGION",
	"ACCESS_KEY_ID",
	"SECRET_ACCESS_KEY",
	"USE_PATH_STYLE",
	"UNSIGNED_PAYLOAD",
	"CREDENTIALS_JSON",
	"TOKEN",
	"REMOTE",
	"RCLONE_CONFIG_PATH",
	"RCLONE_CONFIG_DATA",
}

// Manager owns the storage disks selected by this generated driver manifest.
type Manager struct {
	defaultDisk storage.Storage
}

// ReadinessCheck names a generated storage probe for framework health reporting.
type ReadinessCheck struct {
	Name  string
	Check func(context.Context) error
}

// NewManager builds storage disks from the environment contract captured by this generated artifact.
func NewManager() (*Manager, error) {
	return newManagerFromEnv()
}

// ReadinessChecks exposes one probe per generated disk so health reflects every initialized backend.
func (m *Manager) ReadinessChecks() []ReadinessCheck {
	if m == nil {
		return nil
	}
	return []ReadinessCheck{
		{
			Name: "storage_default",
			Check: func(ctx context.Context) error {
				return storageReadinessCheck(ctx, m.defaultDisk)
			},
		},
	}
}

// LoadConfigFromEnv materializes the generated disk contract for callers that build storage independently.
func LoadConfigFromEnv() (storage.Config, error) {
	storageScope := env.WithPrefix("STORAGE")
	disks, err := loadDisksFromEnv(storageScope)
	if err != nil {
		return storage.Config{}, err
	}
	return storage.Config{
		Default: defaultDiskName,
		Disks:   disks,
	}, nil
}

// loadDisksFromEnv keeps default and named disk parsing under one validation boundary.
func loadDisksFromEnv(storageScope env.Scope) (map[storage.DiskName]storage.DriverConfig, error) {
	disks := map[storage.DiskName]storage.DriverConfig{}

	defaultCfg, err := buildDiskConfig(defaultDiskName, storageScope)
	if err != nil {
		return nil, err
	}
	disks[defaultDiskName] = defaultCfg

	for _, child := range storageScope.ChildNames(storageRootKeys) {
		name := storage.DiskName(str.Of(child).TrimSpace().ToLower().String())
		cfg, err := buildDiskConfig(name, storageScope.Child(child))
		if err != nil {
			return nil, err
		}
		disks[name] = cfg
	}

	return disks, nil
}

// newManagerFromEnv keeps storage construction on the same generated configuration path exposed to callers.
func newManagerFromEnv() (*Manager, error) {
	cfg, err := LoadConfigFromEnv()
	if err != nil {
		return nil, err
	}
	inner, err := storage.New(cfg)
	if err != nil {
		return nil, err
	}
	return &Manager{defaultDisk: inner.Default()}, nil
}

// buildDiskConfig isolates named local disks while applying the generated backend contract.
func buildDiskConfig(name storage.DiskName, scope env.Scope) (storage.DriverConfig, error) {
	driver := str.Of(scope.Get("DRIVER", driverLocal)).TrimSpace().ToLower().String()
	if driver == "" {
		driver = driverLocal
	}

	localRoot := filepath.Join("storage", "app", "private")
	if name != defaultDiskName {
		localRoot = filepath.Join("storage", "app", string(name))
	}

	switch driver {
	case driverLocal:
		root := scope.Get("ROOT", localRoot)
		if err := os.MkdirAll(root, 0o755); err != nil {
			return nil, err
		}
		return localstorage.Config{
			Root:   root,
			Prefix: scope.Get("PREFIX", ""),
		}, nil
	default:
		return nil, fmt.Errorf("storage: unsupported driver %q", driver)
	}
}

// storageReadinessCheck prefers explicit driver health contracts and falls back to a lightweight listing operation.
func storageReadinessCheck(ctx context.Context, disk storage.Storage) error {
	if disk == nil {
		return nil
	}
	if ready, ok := any(disk).(interface{ Ready(context.Context) error }); ok {
		return ready.Ready(ctx)
	}
	if ready, ok := any(disk).(interface{ Ready() error }); ok {
		return ready.Ready()
	}
	_, err := disk.WithContext(ctx).List("")
	return err
}
