project_name: GoForj
module_name: forj
updated_at: 2025-04-27 18:54:57 CDT
pre_dev:
  - name: Run Wire generate
    cmd: go install github.com/google/wire/cmd/wire@latest && cd wire && wire
  - name: Watcher Go Install
    cmd: go install github.com/goforj/wgo@latest
dev_watches:
  - name: App
    watch: -file .env -file .go -file .tmpl
    exec: go run ./cmd/forj/main.go build
  - name: Wire
    watch: -file .go -cd ./wire -xfile ./wire/wire_gen.go -postpone
    exec: wire
components:
  cli: true
