package envfile

import (
	"encoding/base64"
	"path/filepath"
	"strings"
)

const (
	testingContractMarker = "# Managed by GoForj."
	testingContractHeader = "# Selected automatically by goforj/env when tests load the environment. Safe to commit; process variables override these values."
)

// IsManagedTestingContract reports whether a testing profile was generated by the current synchronization policy.
func IsManagedTestingContract(content []byte) bool {
	return containsExactLine(strings.Split(string(content), "\n"), testingContractMarker)
}

// MergeTesting derives a runnable test profile from the safe environment contract while preserving project-owned test values.
func MergeTesting(existing []byte, example []byte) []byte {
	generated := testingContract(example)
	if len(existing) == 0 {
		return generated
	}

	lines := strings.Split(string(RedactExample(existing)), "\n")
	generatedKeys := assignmentKeys(generated)
	retained := lines[:0]
	for _, line := range lines {
		key, _, ok := ParseAssignment(line)
		if ok && isFrameworkTestingKey(key) && !generatedKeys[key] {
			continue
		}
		retained = append(retained, line)
	}
	lines = retained
	indices := activeAssignmentIndices(lines)
	for _, line := range strings.Split(string(generated), "\n") {
		key, _, ok := ParseAssignment(line)
		if !ok {
			continue
		}
		if index, exists := indices[key]; exists {
			if isFrameworkTestingKey(key) {
				lines[index] = line
			}
			continue
		}
		lines = appendBeforeTerminalEmpty(lines, line)
		indices[key] = len(lines) - 1
	}
	if !containsExactLine(lines, testingContractMarker) {
		lines = append([]string{testingContractMarker, testingContractHeader, ""}, lines...)
	}
	merged := strings.Join(lines, "\n")
	if strings.HasSuffix(string(existing), "\n") && !strings.HasSuffix(merged, "\n") {
		merged += "\n"
	}
	return []byte(merged)
}

// assignmentKeys identifies the exact framework contract keys that remain owned by synchronization.
func assignmentKeys(content []byte) map[string]bool {
	keys := make(map[string]bool)
	for _, line := range strings.Split(string(content), "\n") {
		key, _, ok := ParseAssignment(line)
		if ok {
			keys[key] = true
		}
	}
	return keys
}

// testingContract converts every active example assignment into its deterministic test representation.
func testingContract(example []byte) []byte {
	lines := strings.Split(string(example), "\n")
	values := make(map[string]string)
	for _, line := range lines {
		key, value, ok := ParseAssignment(line)
		if ok {
			values[strings.ToUpper(strings.TrimSpace(key))] = value
		}
	}
	out := make([]string, 0, len(lines)+3)
	out = append(out, testingContractMarker, testingContractHeader, "")
	for _, line := range lines {
		key, value, ok := ParseAssignment(line)
		if !ok {
			out = append(out, line)
			continue
		}
		out = append(out, key+"="+EncodeValue(testingValue(key, value, values)))
	}
	return []byte(strings.Join(out, "\n"))
}

// testingValue selects public, deterministic values that cannot be mistaken for deployment credentials.
func testingValue(key string, value string, values map[string]string) string {
	normalized := strings.ToUpper(strings.TrimSpace(key))
	policyKey := testingPolicyKey(normalized)
	switch policyKey {
	case "APP_ENV":
		return "testing"
	case "APP_MAINTENANCE_ENABLED":
		return "false"
	case "APP_MAINTENANCE_DRIVER":
		return "memory"
	case "APP_MAINTENANCE_STORE":
		return "default"
	case "APP_KEY":
		return "base64:" + base64.StdEncoding.EncodeToString([]byte("goforj-public-testing-key-000001"))
	case "APP_DIAG_TOKEN":
		return "goforj-public-testing-diagnostics-token"
	case "LIGHTHOUSE_SECRET":
		return "goforj-public-testing-lighthouse-secret"
	case "API_JWT_SECRET_KEY":
		return "goforj-public-testing-jwt-signing-key-000000000000"
	case "AUTH_BOOTSTRAP_USERNAME", "AUTH_BOOTSTRAP_EMAIL", "AUTH_BOOTSTRAP_PASSWORD":
		return ""
	case "DB_HOST", "REDIS_HOST", "MAIL_SMTP_HOST":
		return "127.0.0.1"
	case "DB_USERNAME":
		return "test"
	case "DB_PASSWORD", "DB_ROOT_PASSWORD":
		return "test"
	case "QUEUE_ACCESS_KEY", "QUEUE_SECRET_KEY":
		return "test"
	case "CACHE_URL", "EVENTS_URL":
		return "nats://goforj:goforj@nats:4222"
	case "QUEUE_URL":
		if strings.EqualFold(strings.TrimSpace(values["QUEUE_DRIVER"]), "rabbitmq") {
			return "amqp://goforj:goforj@rabbitmq:5672/"
		}
		return "nats://goforj:goforj@nats:4222"
	case "DB_DATABASE", "DB_SQLITE_DATABASE":
		return testingDatabase(value)
	}
	if isSensitiveKey(normalized) {
		return ""
	}
	return value
}

// testingPolicyKey applies root policies to app-prefixed forms such as BILLING_DB_PASSWORD.
func testingPolicyKey(key string) string {
	for _, candidate := range []string{
		"APP_ENV", "APP_KEY", "APP_DIAG_TOKEN", "APP_MAINTENANCE_ENABLED", "APP_MAINTENANCE_DRIVER", "APP_MAINTENANCE_STORE", "LIGHTHOUSE_SECRET", "API_JWT_SECRET_KEY",
		"AUTH_BOOTSTRAP_USERNAME", "AUTH_BOOTSTRAP_EMAIL", "AUTH_BOOTSTRAP_PASSWORD",
		"DB_HOST", "REDIS_HOST", "MAIL_SMTP_HOST", "DB_USERNAME", "DB_PASSWORD", "DB_ROOT_PASSWORD",
		"QUEUE_ACCESS_KEY", "QUEUE_SECRET_KEY", "DB_DATABASE", "DB_SQLITE_DATABASE",
		"CACHE_URL", "EVENTS_URL", "QUEUE_URL",
	} {
		if key == candidate || strings.HasSuffix(key, "_"+candidate) {
			return candidate
		}
	}
	return key
}

// testingDatabase isolates test data without changing the configured database driver.
func testingDatabase(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return "app_testing"
	}
	if isSQLiteMemoryDatabase(value) {
		return value
	}
	path, suffix := splitDatabaseSuffix(value)
	extension := filepath.Ext(path)
	switch strings.ToLower(extension) {
	case ".db", ".sqlite", ".sqlite3":
		return strings.TrimSuffix(path, extension) + "_testing" + extension + suffix
	}
	if strings.HasSuffix(path, "_testing") {
		return value
	}
	return path + "_testing" + suffix
}

// isSQLiteMemoryDatabase preserves SQLite's special in-memory DSNs instead of turning them into disk files.
func isSQLiteMemoryDatabase(value string) bool {
	normalized := strings.ToLower(strings.TrimSpace(value))
	return normalized == ":memory:" || strings.HasPrefix(normalized, "file::memory:")
}

// splitDatabaseSuffix keeps URI query and fragment options attached after deriving the isolated database path.
func splitDatabaseSuffix(value string) (string, string) {
	index := strings.IndexAny(value, "?#")
	if index < 0 {
		return value, ""
	}
	return value[:index], value[index:]
}

// isFrameworkTestingKey identifies values whose test policy remains framework-owned across synchronization.
func isFrameworkTestingKey(key string) bool {
	return isFrameworkContractKey(key)
}

var frameworkContractKeys = map[string]bool{
	"API_HTTP_HOST": true, "API_HTTP_PORT": true, "API_JWT_SECRET_KEY": true, "API_SWAGGER_ENABLED": true,
	"APP_DEBUG": true, "APP_DIAG_TOKEN": true, "APP_ENV": true, "APP_KEY": true, "APP_LOG_FORMAT": true,
	"APP_MAINTENANCE_DRIVER": true, "APP_MAINTENANCE_ENABLED": true, "APP_MAINTENANCE_STORE": true,
	"APP_LOG_TIME": true, "APP_NAME": true, "APP_URL": true, "AUTH_BOOTSTRAP_EMAIL": true,
	"AUTH_BOOTSTRAP_PASSWORD": true, "AUTH_BOOTSTRAP_USERNAME": true, "CACHE_ADDRESSES": true,
	"CACHE_DRIVER": true, "CACHE_ENDPOINT": true, "CACHE_REGION": true, "CACHE_SESSIONS_DRIVER": true,
	"CACHE_SETTINGS_DRIVER": true, "CACHE_SUPPORTED_DRIVERS": true, "CACHE_URL": true, "COMPOSE_PROFILES": true,
	"DB_DATABASE": true, "DB_DRIVER": true, "DB_HOST": true, "DB_PASSWORD": true, "DB_PORT": true,
	"DB_ROOT_PASSWORD": true, "DB_SQLITE_DATABASE": true, "DB_SUPPORTED_DRIVERS": true, "DB_USERNAME": true,
	"EVENTS_BROKERS": true, "EVENTS_DRIVER": true, "EVENTS_PROJECT_ID": true, "EVENTS_SUPPORTED_DRIVERS": true,
	"EVENTS_URI": true, "EVENTS_URL": true, "GRAFANA_ADMIN_PASSWORD": true, "GRAFANA_ADMIN_USER": true,
	"GRAFANA_PORT": true, "IP_ADDRESS": true, "LIGHTHOUSE_ENABLED": true, "LIGHTHOUSE_SECRET": true,
	"LIGHTHOUSE_URL": true, "MAILPIT_HTTP_PORT": true, "MAILPIT_SMTP_PORT": true, "MAIL_DRIVER": true,
	"MAIL_FROM_ADDRESS": true, "MAIL_FROM_NAME": true, "MAIL_SMTP_HOST": true, "MAIL_SMTP_PORT": true,
	"MAIL_SUPPORTED_DRIVERS": true, "API_METRICS_PORT": true, "JOBS_METRICS_PORT": true,
	"METRICS_API_PORT": true, "METRICS_JOBS_PORT": true, "METRICS_PORT": true,
	"METRICS_SCHEDULER_PORT": true, "SCHEDULER_METRICS_PORT": true, "WORKER_METRICS_PORT": true,
	"OBSERVABILITY_VM_PORT": true, "QUEUE_ACCESS_KEY": true,
	"QUEUE_DRIVER": true, "QUEUE_ENDPOINT": true, "QUEUE_REGION": true, "QUEUE_SECRET_KEY": true,
	"QUEUE_SHUTDOWN_TIMEOUT": true, "QUEUE_SUPPORTED_DRIVERS": true, "QUEUE_URL": true, "QUEUE_WORKERS": true,
	"REDIS_DB": true, "REDIS_HOST": true, "REDIS_PASSWORD": true, "REDIS_PORT": true,
	"SCHEDULER_SUBPROCESS_SHUTDOWN_TIMEOUT": true, "STORAGE_DRIVER": true, "STORAGE_FAVICONS_DRIVER": true,
	"STORAGE_FAVICONS_ROOT": true, "STORAGE_PUBLIC_DRIVER": true, "STORAGE_PUBLIC_ROOT": true,
	"STORAGE_ROOT": true, "STORAGE_SUPPORTED_DRIVERS": true, "TZ": true,
}

// isFrameworkContractKey matches only rendered framework keys and their named-App overlays.
func isFrameworkContractKey(key string) bool {
	normalized := strings.ToUpper(strings.TrimSpace(key))
	if frameworkContractKeys[normalized] {
		return true
	}
	for candidate := range frameworkContractKeys {
		if strings.HasSuffix(normalized, "_"+candidate) {
			return true
		}
	}
	return false
}

// activeAssignmentIndices records the controlling assignment for each active key.
func activeAssignmentIndices(lines []string) map[string]int {
	indices := make(map[string]int)
	for index, line := range lines {
		key, _, ok := ParseAssignment(line)
		if ok {
			indices[key] = index
		}
	}
	return indices
}

// appendBeforeTerminalEmpty retains the existing newline convention while adding a missing assignment.
func appendBeforeTerminalEmpty(lines []string, line string) []string {
	if len(lines) > 0 && lines[len(lines)-1] == "" {
		lines[len(lines)-1] = line
		return append(lines, "")
	}
	return append(lines, line)
}

// containsExactLine reports whether a generated ownership note is already present.
func containsExactLine(lines []string, want string) bool {
	for _, line := range lines {
		if line == want {
			return true
		}
	}
	return false
}
