// Code generated by forj generate --queue. DO NOT EDIT.
// Run: forj generate --queue
//
// These queue manager accessors are derived from the current .env file
// and environment variables available when generation ran.
// Named accessors are generated from QUEUE_<NAME>_<KEY> environment variables.
package queues

import (
	"github.com/goforj/queue"
	"github.com/goforj/str/v2"
)

// Default returns the default queue instance derived from QUEUE_* configuration.
func (m *Manager) Default() *queue.Queue {
	return m.defaultQueue
}

// Critical returns the "critical" queue instance.
func (m *Manager) Critical() *queue.Queue {
	return m.critical
}

// Names returns the generated queue names derived from QUEUE_* configuration.
func (m *Manager) Names() []string {
	names := []string{"default"}
	if m.critical != nil {
		names = append(names, "critical")
	}
	return names
}

// Named returns the generated queue instance for a configured queue name.
func (m *Manager) Named(name string) *queue.Queue {
	switch str.Of(name).Trim().ToLower().String() {
	case "", "default":
		return m.defaultQueue
	case "critical":
		return m.critical
	default:
		return nil
	}
}
