// Code generated by forj generate --queue. DO NOT EDIT.
// Run: forj generate --queue
package queues

import (
	"context"
	"fmt"
	"strings"

	"github.com/goforj/env/v2"
	"github.com/goforj/queue"
	"github.com/goforj/str/v2"
)

const defaultQueueName = "default"

const (
	driverMySQL      = "mysql"
	driverNATS       = "nats"
	driverNull       = "null"
	driverPostgres   = "postgres"
	driverRabbitMQ   = "rabbitmq"
	driverRedis      = "redis"
	driverSQLite     = "sqlite"
	driverSQS        = "sqs"
	driverSync       = "sync"
	driverWorkerpool = "workerpool"
)

var queueRootKeys = []string{
	"DRIVER",
	"WORKERS",
	"NAME",
	"DEFAULT_QUEUE",
	"ADDR",
	"PASSWORD",
	"DB",
	"QUEUES",
	"SERVER_LOG_LEVEL",
	"URL",
	"REGION",
	"ENDPOINT",
	"ACCESS_KEY",
	"SECRET_KEY",
	"DSN",
	"WORKERPOOL_WORKERS",
	"WORKERPOOL_BUFFER",
	"WORKERPOOL_TASK_TIMEOUT_SECONDS",
	"PROCESSING_RECOVERY_GRACE_SECONDS",
	"PROCESSING_LEASE_NO_TIMEOUT_SECONDS",
}

// Manager owns the queue instances selected by this generated driver manifest.
type Manager struct {
	defaultQueue *queue.Queue
	critical     *queue.Queue
}

// ReadinessCheck names a generated queue probe for framework health reporting.
type ReadinessCheck struct {
	Name  string
	Check func(context.Context) error
}

// NewManager builds configured queues without optional runtime instrumentation.
func NewManager() (*Manager, error) {
	return NewManagerWithObserver(nil, nil)
}

// NewManagerWithObserver centralizes queue construction when runtime instrumentation is available.
func NewManagerWithObserver(observer queue.Observer, logger queue.Logger) (*Manager, error) {
	return newManagerFromEnv(env.WithPrefix("QUEUE"), observer, logger)
}

// ReadinessChecks exposes an independently named health probe for every generated queue.
func (m *Manager) ReadinessChecks() []ReadinessCheck {
	checks := []ReadinessCheck{
		{
			Name: "queue_default",
			Check: func(ctx context.Context) error {
				return m.defaultQueue.Ready(ctx)
			},
		},
	}
	if m.critical != nil {
		checks = append(checks, ReadinessCheck{
			Name: "queue_critical",
			Check: func(ctx context.Context) error {
				return m.critical.Ready(ctx)
			},
		})
	}
	return checks
}

// newManagerFromEnv keeps default and named queues on the same scoped configuration path.
func newManagerFromEnv(queueScope env.Scope, observer queue.Observer, logger queue.Logger) (*Manager, error) {
	defaultQueue, err := buildQueue(defaultQueueName, queueScope, observer, logger)
	if err != nil {
		return nil, err
	}
	manager := &Manager{defaultQueue: defaultQueue}

	for _, child := range queueScope.ChildNames(queueRootKeys) {
		name := str.Of(child).Trim().ToLower().String()
		if name == "" {
			continue
		}
		queueInstance, err := buildQueue(name, queueScope.Child(child), observer, logger)
		if err != nil {
			return nil, err
		}
		switch name {
		case "critical":
			manager.critical = queueInstance
		}
	}

	return manager, nil
}

// buildQueue applies the generated transport contract before queue infrastructure is initialized.
func buildQueue(_ string, scope env.Scope, observer queue.Observer, logger queue.Logger) (*queue.Queue, error) {
	driver := str.Of(scope.Get("DRIVER", driverWorkerpool)).Trim().ToLower().String()
	if driver == "" {
		driver = driverWorkerpool
	}

	defaultQueue := queueDefaultQueue(scope)
	options := []queue.Option{
		queue.WithWorkers(queueWorkerCount(scope)),
	}

	switch driver {
	case driverNull:
		return queue.New(queue.Config{
			Driver:       queue.DriverNull,
			DefaultQueue: defaultQueue,
			Observer:     observer,
			Logger:       logger,
		}, options...)
	case driverSync:
		return queue.New(queue.Config{
			Driver:       queue.DriverSync,
			DefaultQueue: defaultQueue,
			Observer:     observer,
			Logger:       logger,
		}, options...)
	case driverWorkerpool:
		return queue.New(queue.Config{
			Driver:       queue.DriverWorkerpool,
			DefaultQueue: defaultQueue,
			Observer:     observer,
			Logger:       logger,
		}, options...)
	default:
		return nil, fmt.Errorf("queue: unsupported driver %q", driver)
	}
}

// queueWorkerCount preserves a usable worker pool when configuration is missing or non-positive.
func queueWorkerCount(scope env.Scope) int {
	workers := scope.GetInt("WORKERS", "30")
	if workers <= 0 {
		workers = scope.GetInt("WORKERPOOL_WORKERS", "30")
	}
	if workers <= 0 {
		return 30
	}
	return workers
}

// queueDefaultQueue retains legacy naming while preferring the current queue-name setting.
func queueDefaultQueue(scope env.Scope) string {
	value := strings.TrimSpace(scope.Get("NAME", ""))
	if value == "" {
		value = strings.TrimSpace(scope.Get("DEFAULT_QUEUE", "default"))
	}
	if value == "" {
		return "default"
	}
	return value
}
