// Code generated by scripts/generate-renderwarm.sh; DO NOT EDIT.

module github.com/goforj/goforj/tools/renderwarm

go 1.25.0

require (
	github.com/alecthomas/kong v1.14.0
	github.com/charmbracelet/lipgloss v1.1.0
	github.com/glebarez/sqlite v1.11.0
	github.com/goforj/cache v0.1.5
	github.com/goforj/cache/cachecore v0.1.5
	github.com/goforj/crypt v1.0.0
	github.com/goforj/env/v2 v2.3.1
	github.com/goforj/events v0.1.0
	github.com/goforj/events/eventscore v0.1.0
	github.com/goforj/httpx v1.1.0
	github.com/goforj/null/v6 v6.0.2
	github.com/goforj/queue v0.1.6
	github.com/goforj/scheduler v1.4.0
	github.com/goforj/str v1.2.0
	github.com/google/uuid v1.6.0
	github.com/google/wire v0.6.0
	github.com/gorilla/websocket v1.5.3
	github.com/jedib0t/go-pretty/v6 v6.7.8
	github.com/klauspost/compress v1.18.4
	github.com/labstack/echo/v4 v4.15.1
	github.com/rs/zerolog v1.34.0
	github.com/shirou/gopsutil/v4 v4.26.2
	github.com/stretchr/testify v1.11.1
	golang.org/x/net v0.48.0
	golang.org/x/term v0.40.0
	golang.org/x/tools v0.38.0
	gopkg.in/yaml.v3 v3.0.1
	gorm.io/driver/mysql v1.6.0
	gorm.io/driver/postgres v1.6.0
	gorm.io/gorm v1.30.0
)
