// Code generated by scripts/generate-renderwarm.sh; DO NOT EDIT.

module github.com/goforj/goforj/tools/renderwarm

go 1.26.0

require (
	github.com/a-h/templ v0.3.1020
	github.com/alecthomas/kong v1.15.0
	github.com/charmbracelet/bubbles v0.21.0
	github.com/charmbracelet/bubbletea v1.3.4
	github.com/charmbracelet/lipgloss v1.1.0
	github.com/glebarez/sqlite v1.11.0
	github.com/goforj/cache v0.4.0
	github.com/goforj/cache/cachecore v0.4.0
	github.com/goforj/cache/driver/rediscache v0.4.0
	github.com/goforj/console v0.2.0
	github.com/goforj/crypt v1.2.0
	github.com/goforj/env/v2 v2.6.1
	github.com/goforj/events v0.2.0
	github.com/goforj/events/eventscore v0.2.0
	github.com/goforj/godump v1.9.1
	github.com/goforj/httpx v1.1.0
	github.com/goforj/mail v0.3.1
	github.com/goforj/metrics v0.2.0
	github.com/goforj/null/v6 v6.0.2
	github.com/goforj/queue v0.2.1
	github.com/goforj/scheduler/v2 v2.1.4
	github.com/goforj/storage v0.5.0
	github.com/goforj/str v1.3.0
	github.com/goforj/str/v2 v2.0.1
	github.com/goforj/web v0.6.2
	github.com/goforj/wire v1.2.0
	github.com/golang-jwt/jwt/v5 v5.3.1
	github.com/google/uuid v1.6.0
	github.com/gorilla/websocket v1.5.3
	github.com/joho/godotenv v1.5.1
	github.com/klauspost/compress v1.18.7
	github.com/moby/go-archive v0.3.3
	github.com/refraction-networking/utls v1.8.2
	github.com/rs/zerolog v1.34.0
	github.com/shirou/gopsutil/v4 v4.26.2
	github.com/stretchr/testify v1.11.1
	github.com/testcontainers/testcontainers-go v0.41.0
	github.com/vmihailenco/msgpack/v5 v5.4.1
	golang.org/x/crypto v0.56.0
	golang.org/x/net v0.57.0
	golang.org/x/oauth2 v0.36.0
	golang.org/x/term v0.45.0
	golang.org/x/tools v0.48.0
	gopkg.in/yaml.v3 v3.0.1
	gorm.io/driver/mysql v1.6.0
	gorm.io/driver/postgres v1.6.0
	gorm.io/gorm v1.26.0
)
