//go:build integration

package forj

import (
	"bytes"
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/glebarez/sqlite"
	"github.com/goforj/goforj/internal/testkit"
	"github.com/goforj/goforj/project"
	"gorm.io/gorm"
)

func TestMakeFlowsIntegration(t *testing.T) {
	projectDir := t.TempDir()
	renderAppAtDir(t, projectDir)
	binPath := testkit.EnsureIntegrationForjBinary(t)
	_ = testkit.EnsureIntegrationToolsDir(t)

	runForj := func(tb testing.TB, args ...string) string {
		tb.Helper()
		ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
		defer cancel()
		cmd := exec.CommandContext(ctx, binPath, args...)
		cmd.Dir = projectDir
		cmd.Env = testkit.IntegrationProcessEnv(t, nil)
		var out bytes.Buffer
		cmd.Stdout = &out
		cmd.Stderr = &out
		if err := cmd.Run(); err != nil {
			tb.Fatalf("forj %s failed: %v\n%s", strings.Join(args, " "), err, out.String())
		}
		return out.String()
	}

	runForjFailure := func(tb testing.TB, args ...string) string {
		tb.Helper()
		ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
		defer cancel()
		cmd := exec.CommandContext(ctx, binPath, args...)
		cmd.Dir = projectDir
		cmd.Env = testkit.IntegrationProcessEnv(t, nil)
		var out bytes.Buffer
		cmd.Stdout = &out
		cmd.Stderr = &out
		if err := cmd.Run(); err == nil {
			tb.Fatalf("forj %s unexpectedly succeeded\n%s", strings.Join(args, " "), out.String())
		}
		return out.String()
	}

	buildApp := func(tb testing.TB) {
		tb.Helper()
		ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
		defer cancel()
		cmd := exec.CommandContext(ctx, binPath, "build", "-o", "./bin/app")
		cmd.Dir = projectDir
		cmd.Env = testkit.IntegrationGoProcessEnv(t, nil)
		var out bytes.Buffer
		cmd.Stdout = &out
		cmd.Stderr = &out
		if err := cmd.Run(); err != nil {
			tb.Fatalf("forj build failed: %v\n%s", err, out.String())
		}
		if _, err := os.Stat(filepath.Join(projectDir, "bin", "app")); err != nil {
			tb.Fatalf("expected built app binary: %v", err)
		}
	}

	runApp := func(tb testing.TB, args ...string) string {
		tb.Helper()
		ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
		defer cancel()
		cmd := exec.CommandContext(ctx, filepath.Join(projectDir, "bin", "app"), args...)
		cmd.Dir = projectDir
		cmd.Env = testkit.IntegrationProcessEnv(t, nil)
		var out bytes.Buffer
		cmd.Stdout = &out
		cmd.Stderr = &out
		if err := cmd.Run(); err != nil {
			tb.Fatalf("app %s failed: %v\n%s", strings.Join(args, " "), err, out.String())
		}
		return out.String()
	}

	runForj(t, "make:controller", "Audit")
	runForj(t, "make:controller", "Audit")
	assertFileContains(t, filepath.Join(projectDir, "internal", "audit", "controller.go"), []string{
		"package audit",
		`web.NewRoute(http.MethodGet, "/audit", c.Get)`,
	})
	assertFileContains(t, filepath.Join(projectDir, "app", "wire", "inject_http_controllers_app.go"), []string{
		`"example.com/testapp/internal/audit"`,
		"audit.NewController",
	})
	assertFileContains(t, filepath.Join(projectDir, "app", "routes.go"), []string{
		`"example.com/testapp/internal/audit"`,
		"auditController *audit.Controller",
		"auditController.Routes(),",
	})

	runForj(t, "make:controller", "Billing:Reports")
	assertFileContains(t, filepath.Join(projectDir, "internal", "billing", "reports", "controller.go"), []string{
		"package reports",
		`web.NewRoute(http.MethodGet, "/billing/reports", c.Get)`,
	})
	assertFileContains(t, filepath.Join(projectDir, "app", "wire", "inject_http_controllers_app.go"), []string{
		`billingReports "example.com/testapp/internal/billing/reports"`,
		"billingReports.NewController",
	})
	assertFileContains(t, filepath.Join(projectDir, "app", "routes.go"), []string{
		`billingReports "example.com/testapp/internal/billing/reports"`,
		"billingReportsController *billingReports.Controller",
		"billingReportsController.Routes(),",
	})

	runForj(t, "make:event", "UserRegistered")
	assertFileContains(t, filepath.Join(projectDir, "internal", "events", "user_registered_event.go"), []string{
		"package events",
		"const UserRegisteredEventTopic",
		"type UserRegisteredEvent struct",
	})
	runForj(t, "make:event", "Billing:InvoicePaid")
	assertFileContains(t, filepath.Join(projectDir, "internal", "billing", "invoice_paid_event.go"), []string{
		"package billing",
		"const InvoicePaidEventTopic",
		"type InvoicePaidEvent struct",
	})
	runForj(t, "make:subscriber", "Billing:InvoicePaid")
	assertFileContains(t, filepath.Join(projectDir, "internal", "billing", "invoice_paid_subscriber.go"), []string{
		"package billing",
		"// Generated by `forj make:subscriber`. Edit this App-owned subscriber.",
		"type InvoicePaidSubscriber struct",
		"func NewInvoicePaidSubscriber() *InvoicePaidSubscriber",
		"func (s *InvoicePaidSubscriber) Handle(ctx context.Context, event InvoicePaidEvent) error",
	})
	assertFileContains(t, filepath.Join(projectDir, "app", "wire", "inject_subscribers_app.go"), []string{
		"// App-owned Wire injector. EDIT THIS FILE.",
		"// Add application event subscriber providers here, or use `forj make:subscriber`.",
		`"example.com/testapp/internal/billing"`,
		"billing.NewInvoicePaidSubscriber",
		`eventManager.Named("default")`,
		"billingInvoicePaidSubscriber.Handle",
	})

	runForj(t, "make:queue", "reports", "--workers", "2", "--name", "production-report-jobs")
	assertFileContains(t, filepath.Join(projectDir, ".env"), []string{
		"# Queue",
		"# Named queues can prioritize work by allocating workers:",
		"QUEUE_REPORTS_NAME=production-report-jobs",
		"QUEUE_REPORTS_WORKERS=2",
	})
	assertFileNotContains(t, filepath.Join(projectDir, ".env"), []string{
		"# QUEUE_REPORTS_NAME=reports",
		"# QUEUE_REPORTS_WORKERS=2",
		"QUEUE_QUEUES",
	})
	runForj(t, "make:queue", "reports", "--workers", "4")
	assertFileContains(t, filepath.Join(projectDir, ".env"), []string{
		"QUEUE_REPORTS_NAME=reports",
		"QUEUE_REPORTS_WORKERS=4",
	})

	runForj(t, "make:job", "SyncReports", "--queue", "reports")
	assertFileContains(t, filepath.Join(projectDir, "internal", "jobs", "sync_reports_job.go"), []string{
		"package jobs",
		"const SyncReportsJobTypeName",
		"type SyncReportsJob struct",
		`.OnQueue("reports")`,
	})
	assertFileContains(t, filepath.Join(projectDir, "app", "wire", "inject_jobs_app.go"), []string{
		"jobs.NewSyncReportsJob",
	})
	runForj(t, "make:job", "Billing:SyncReports")
	assertFileContains(t, filepath.Join(projectDir, "internal", "billing", "sync_reports_job.go"), []string{
		"package billing",
		"const SyncReportsJobTypeName",
		"type SyncReportsJob struct",
	})
	assertFileContains(t, filepath.Join(projectDir, "app", "wire", "inject_jobs_app.go"), []string{
		`"example.com/testapp/internal/billing"`,
		"billing.NewSyncReportsJob",
	})

	runForj(t, "make:migration", "create_widgets")
	assertGlob(t, filepath.Join(projectDir, "migrations", "*create_widgets.up.sql"))
	assertGlob(t, filepath.Join(projectDir, "migrations", "*create_widgets.down.sql"))

	runForj(t, "make:schedule", "Reports:Daily", "--every", "24h")
	assertFileContains(t, filepath.Join(projectDir, "internal", "reports", "daily_schedule.go"), []string{
		"package reports",
		"// Generated by `forj make:schedule`. Edit this App-owned schedule.",
		`const DailyScheduleName = "reports:daily"`,
		`const DailyScheduleInterval = "24h"`,
		"type DailySchedule struct",
		"func (s *DailySchedule) Name() string",
		"func (s *DailySchedule) Interval() (time.Duration, error)",
	})
	assertFileNotContains(t, filepath.Join(projectDir, "internal", "reports", "daily_schedule.go"), []string{
		"schedulerx",
		"github.com/goforj/scheduler",
	})
	assertFileContains(t, filepath.Join(projectDir, "internal", "schedules", "scheduler.go"), []string{
		"// Code generated by GoForj CLI. DO NOT EDIT.",
		"// App-owned schedule providers belong in app/wire/inject_schedules_app.go.",
		"appSchedules *AppSchedules",
		"appSchedules:",
	})
	assertFileNotContains(t, filepath.Join(projectDir, "internal", "schedules", "scheduler.go"), []string{
		`"example.com/testapp/internal/reports"`,
		"dailySchedule *reports.DailySchedule",
	})
	assertFileContains(t, filepath.Join(projectDir, "internal", "schedules", "scheduler_registry.go"), []string{
		"if err := s.registerAppSchedules(); err != nil {",
		"func (s *Scheduler) registerAppSchedules() error",
		"s.EveryDuration(interval).Name(schedule.Name()).Do(s.inspectTask(schedule.Name(), schedule.Handle))",
	})
	assertFileContains(t, filepath.Join(projectDir, "app", "wire", "inject_schedules_app.go"), []string{
		"// App-owned Wire injector. EDIT THIS FILE.",
		"// Add application schedule providers here, or use `forj make:schedule`.",
		`"example.com/testapp/internal/reports"`,
		"reports.NewDailySchedule",
		"dailySchedule *reports.DailySchedule",
		"dailySchedule,",
	})

	legacyScheduleInjector := `package wire

import (
	"github.com/goforj/wire"
	"example.com/testapp/internal/reports"
	"example.com/testapp/internal/scheduler"
)

var appScheduleSet = wire.NewSet(
	ProvideAppSchedules,
	reports.NewDailySchedule,
)

func ProvideAppSchedules(
	dailySchedule *reports.DailySchedule,
) *scheduler.AppSchedules {
	return scheduler.NewAppSchedules(
		dailySchedule,
	)
}
`
	scheduleInjectorPath := filepath.Join(projectDir, "app", "wire", "inject_schedules_app.go")
	if err := os.WriteFile(scheduleInjectorPath, []byte(legacyScheduleInjector), 0o644); err != nil {
		t.Fatalf("write legacy schedule injector: %v", err)
	}
	renderAppAtDir(t, projectDir)
	assertFileContains(t, scheduleInjectorPath, []string{
		`"example.com/testapp/internal/schedules"`,
		`"example.com/testapp/internal/reports"`,
		"reports.NewDailySchedule",
		"*schedules.AppSchedules",
		"return schedules.NewAppSchedules(",
		"dailySchedule *reports.DailySchedule",
		"dailySchedule,",
	})
	assertFileNotContains(t, scheduleInjectorPath, []string{
		`"example.com/testapp/internal/scheduler"`,
		"scheduler.AppSchedules",
		"scheduler.NewAppSchedules",
	})

	scheduleHelp := runForj(t, "make:schedule", "--help")
	if !strings.Contains(scheduleHelp, "Examples") || !strings.Contains(scheduleHelp, "forj make:schedule reports:daily --every 24h") {
		t.Fatalf("expected make:schedule help to include example, got:\n%s", scheduleHelp)
	}

	missingScheduleNameOutput := runForjFailure(t, "make:schedule")
	if !strings.Contains(missingScheduleNameOutput, `expected "<name>"`) {
		t.Fatalf("expected missing schedule name error, got:\n%s", missingScheduleNameOutput)
	}
	if !strings.Contains(missingScheduleNameOutput, "example: forj make:schedule reports:daily --every 24h") {
		t.Fatalf("expected missing schedule name error to include example, got:\n%s", missingScheduleNameOutput)
	}
	if strings.Contains(missingScheduleNameOutput, "Error executing command") || strings.Contains(missingScheduleNameOutput, "System") {
		t.Fatalf("expected console error output without app logger noise, got:\n%s", missingScheduleNameOutput)
	}
	if strings.Contains(missingScheduleNameOutput, "exit status") || strings.Contains(missingScheduleNameOutput, "go run:") {
		t.Fatalf("expected app command parse error without process wrapper noise, got:\n%s", missingScheduleNameOutput)
	}

	queueHelp := runForj(t, "make:queue", "--help")
	if !strings.Contains(queueHelp, "Examples") || !strings.Contains(queueHelp, "forj make:queue emails --workers 6") {
		t.Fatalf("expected make:queue help to include example, got:\n%s", queueHelp)
	}

	subscriberHelp := runForj(t, "make:subscriber", "--help")
	if !strings.Contains(subscriberHelp, "Examples") || !strings.Contains(subscriberHelp, "forj make:subscriber billing:invoice-paid") {
		t.Fatalf("expected make:subscriber help to include example, got:\n%s", subscriberHelp)
	}

	missingQueueNameOutput := runForjFailure(t, "make:queue", "--workers", "6")
	if !strings.Contains(missingQueueNameOutput, "missing queue name") {
		t.Fatalf("expected missing queue name error, got:\n%s", missingQueueNameOutput)
	}
	if !strings.Contains(missingQueueNameOutput, "example: forj make:queue emails --workers 6") {
		t.Fatalf("expected missing queue name error to include example, got:\n%s", missingQueueNameOutput)
	}
	if strings.Contains(missingQueueNameOutput, "Error executing command") || strings.Contains(missingQueueNameOutput, "System") {
		t.Fatalf("expected console error output without app logger noise, got:\n%s", missingQueueNameOutput)
	}

	missingQueueWorkersOutput := runForjFailure(t, "make:queue", "emails")
	if !strings.Contains(missingQueueWorkersOutput, "missing workers") {
		t.Fatalf("expected missing queue workers error, got:\n%s", missingQueueWorkersOutput)
	}

	composedHelp := runForj(t, "--help")
	for _, want := range []string{"GoForj CLI", "make:command", "route:list", "make:job", "make:queue", "make:subscriber"} {
		if !strings.Contains(composedHelp, want) {
			t.Fatalf("expected composed help to include %s, got:\n%s", want, composedHelp)
		}
	}
	for _, unexpected := range []string{"Framework Commands", "Application Commands", "Generators", "Migrations", "Unknown commands are delegated to this app.", "────"} {
		if strings.Contains(composedHelp, unexpected) {
			t.Fatalf("expected composed help not to include %s, got:\n%s", unexpected, composedHelp)
		}
	}

	sourceRoutes := runForj(t, "route:list")
	if !strings.Contains(sourceRoutes, "/audit") {
		t.Fatalf("expected delegated forj route:list to include generated audit route, got:\n%s", sourceRoutes)
	}
	if !strings.Contains(sourceRoutes, "/billing/reports") {
		t.Fatalf("expected delegated forj route:list to include generated billing reports route, got:\n%s", sourceRoutes)
	}

	buildApp(t)
	routes := runApp(t, "route:list")
	if !strings.Contains(routes, "/audit") {
		t.Fatalf("expected route:list to include generated audit route, got:\n%s", routes)
	}
	if !strings.Contains(routes, "/billing/reports") {
		t.Fatalf("expected route:list to include generated billing reports route, got:\n%s", routes)
	}
}

func TestMakeModelFlowIntegration(t *testing.T) {
	projectDir := t.TempDir()
	testkit.RenderProjectWithForj(t, projectDir, testkit.RenderProjectRequest{
		Config: project.Config{
			ProjectName:  "TestApp",
			GoModuleName: "example.com/testapp",
			UpdatedAt:    "2026-01-01 00:00:00 UTC",
			Render: project.RenderConfig{
				Components: project.Components{
					WebAPI:         true,
					DatabaseSQLite: true,
				},
			},
		},
	})

	dbPath := filepath.Join(projectDir, "_data", "sqlite", "app.db")
	seedSQLiteMakeModelTable(t, dbPath)

	binPath := testkit.EnsureIntegrationForjBinary(t)
	runForj := func(tb testing.TB, args ...string) string {
		tb.Helper()
		ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
		defer cancel()
		cmd := exec.CommandContext(ctx, binPath, args...)
		cmd.Dir = projectDir
		cmd.Env = testkit.IntegrationProcessEnv(t, nil)
		var out bytes.Buffer
		cmd.Stdout = &out
		cmd.Stderr = &out
		if err := cmd.Run(); err != nil {
			tb.Fatalf("forj %s failed: %v\n%s", strings.Join(args, " "), err, out.String())
		}
		return out.String()
	}

	runForjFailure := func(tb testing.TB, args ...string) string {
		tb.Helper()
		ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
		defer cancel()
		cmd := exec.CommandContext(ctx, binPath, args...)
		cmd.Dir = projectDir
		cmd.Env = testkit.IntegrationProcessEnv(t, nil)
		var out bytes.Buffer
		cmd.Stdout = &out
		cmd.Stderr = &out
		if err := cmd.Run(); err == nil {
			tb.Fatalf("forj %s unexpectedly succeeded\n%s", strings.Join(args, " "), out.String())
		}
		return out.String()
	}

	missingModelNameOutput := runForjFailure(t, "make:model")
	if !strings.Contains(missingModelNameOutput, `expected "<table>"`) {
		t.Fatalf("expected missing model table error, got:\n%s", missingModelNameOutput)
	}
	if !strings.Contains(missingModelNameOutput, "example: forj make:model users") {
		t.Fatalf("expected missing model table error to include example, got:\n%s", missingModelNameOutput)
	}
	if strings.Contains(missingModelNameOutput, "initializing application") ||
		strings.Contains(missingModelNameOutput, "exit status") ||
		strings.Contains(missingModelNameOutput, "go run:") {
		t.Fatalf("expected make:model parse error without app boot or process wrapper noise, got:\n%s", missingModelNameOutput)
	}

	runForj(t, "make:model", "widgets")
	runForj(t, "make:model", "widgets")

	assertFileContains(t, filepath.Join(projectDir, "internal", "models", "widget.go"), []string{
		"type Widget struct",
		`gorm:"column:name`,
		`func (*Widget) TableName() string`,
		"type WidgetRepo struct",
		"func NewWidgetRepo(",
	})
	assertFileContains(t, filepath.Join(projectDir, "app", "wire", "inject_repositories_app.go"), []string{
		"models.NewWidgetRepo",
	})

	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, binPath, "build", "-o", "./bin/app")
	cmd.Dir = projectDir
	cmd.Env = testkit.IntegrationGoProcessEnv(t, nil)
	var out bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = &out
	if err := cmd.Run(); err != nil {
		t.Fatalf("forj build failed after make:model: %v\n%s", err, out.String())
	}
}

// seedSQLiteMakeModelTable creates a small schema that exercises make:model repository wiring.
func seedSQLiteMakeModelTable(t *testing.T, dbPath string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(dbPath), 0755); err != nil {
		t.Fatalf("prepare sqlite dir: %v", err)
	}
	db, err := gorm.Open(sqlite.Open(dbPath), &gorm.Config{})
	if err != nil {
		t.Fatalf("open sqlite db: %v", err)
	}
	sqlDB, err := db.DB()
	if err != nil {
		t.Fatalf("sqlite sql db: %v", err)
	}
	t.Cleanup(func() {
		_ = sqlDB.Close()
	})
	if err := db.Exec(`CREATE TABLE widgets (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL,
		enabled BOOLEAN NOT NULL DEFAULT 1,
		created_at DATETIME NULL
	)`).Error; err != nil {
		t.Fatalf("create widgets table: %v", err)
	}
}

// assertGlob verifies generators created at least one timestamped file for the requested pattern.
func assertGlob(t *testing.T, pattern string) {
	t.Helper()
	matches, err := filepath.Glob(pattern)
	if err != nil {
		t.Fatalf("glob %s: %v", pattern, err)
	}
	if len(matches) == 0 {
		t.Fatalf("expected at least one match for %s", pattern)
	}
}

// assertFileNotContains verifies forbidden snippets are absent from a file.
func assertFileNotContains(t *testing.T, path string, forbidden []string) {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	content := string(data)
	for _, value := range forbidden {
		if strings.Contains(content, value) {
			t.Fatalf("unexpected %q in %s\n\n%s", value, path, content)
		}
	}
}
