package forj

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/goforj/goforj/internal/projectlayout"
	"github.com/goforj/goforj/project"
)

// cacheGeneratedCleanupArtifact describes the ownership marker required before Cache cleanup may remove a file.
type cacheGeneratedCleanupArtifact struct {
	path   string
	marker string
}

// cacheGeneratedCleanupArtifacts returns every Cache artifact whose ownership must be proven before removal.
func cacheGeneratedCleanupArtifacts() []cacheGeneratedCleanupArtifact {
	const goSourceMarker = "// Code generated by GoForj CLI. DO NOT EDIT."
	return []cacheGeneratedCleanupArtifact{
		{path: filepath.Join("internal", "caches", "README.md"), marker: "<!-- Code generated by GoForj CLI. DO NOT EDIT. -->"},
		{path: filepath.Join("internal", "caches", "accessors_gen.go"), marker: "// Code generated by forj generate --cache. DO NOT EDIT."},
		{path: filepath.Join("internal", "caches", "manager_gen.go"), marker: "// Code generated by forj generate --cache. DO NOT EDIT."},
		{path: filepath.Join("internal", "cmd", "cache_shell_cmd.go"), marker: goSourceMarker},
		{path: filepath.Join("internal", "observability", "cache_observer.go"), marker: goSourceMarker},
		{path: filepath.Join("internal", "observability", "cache_observer_test.go"), marker: goSourceMarker},
		{path: filepath.Join("internal", "metrics", "cache_metrics_gen.go"), marker: goSourceMarker},
		{path: filepath.Join("internal", "metrics", "cache_metrics_gen_test.go"), marker: goSourceMarker},
		{path: filepath.Join("containers", "observability", "grafana", "dashboards", "cache-overview.json"), marker: `"description": "Code generated by GoForj CLI. DO NOT EDIT."`},
	}
}

// validateCacheGeneratedCleanupArtifacts prevents Cache removal from deleting files whose framework ownership is no longer explicit.
func validateCacheGeneratedCleanupArtifacts() error {
	for _, artifact := range cacheGeneratedCleanupArtifacts() {
		contents, err := os.ReadFile(artifact.path)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return fmt.Errorf("inspect generated Cache artifact %s: %w", artifact.path, err)
		}
		if !strings.Contains(string(contents), artifact.marker) {
			return fmt.Errorf("Cache is disabled but %s does not carry the generated ownership marker; preserve or move it before rendering", artifact.path)
		}
	}
	return nil
}

// validateCacheRenderTransition allows generated Cache cleanup while rejecting files the App owns.
func validateCacheRenderTransition(components project.Components) error {
	if components.Cache {
		return nil
	}
	if err := validateCacheGeneratedCleanupArtifacts(); err != nil {
		return err
	}
	entries, err := os.ReadDir(filepath.Join("internal", "caches"))
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	generated := map[string]struct{}{
		"README.md":        {},
		"accessors_gen.go": {},
		"manager_gen.go":   {},
	}
	for _, entry := range entries {
		if _, ok := generated[entry.Name()]; ok && !entry.IsDir() {
			continue
		}
		return fmt.Errorf("Cache is disabled but internal/caches/%s is not a generated Cache artifact; move or remove it before rendering", entry.Name())
	}
	return nil
}

// cleanupDisabledCacheGeneratedFiles removes only framework-owned Cache artifacts after transition validation succeeds.
func cleanupDisabledCacheGeneratedFiles() error {
	if err := validateCacheGeneratedCleanupArtifacts(); err != nil {
		return err
	}
	for _, artifact := range cacheGeneratedCleanupArtifacts() {
		if err := removeIfExists(artifact.path); err != nil {
			return err
		}
	}
	_, err := removeEmptyDirIfEmpty(filepath.Join("internal", "caches"))
	return err
}

// validateEventsRenderTransition rejects unsupported removal states before rendering can leave a stale Events surface behind.
func (p *ProjectRenderer) validateEventsRenderTransition(projectComponents project.Components) error {
	if !projectComponents.Events {
		for _, path := range projectEventsResiduePaths() {
			if exists, err := renderPathExists(path); err != nil {
				return err
			} else if exists {
				return fmt.Errorf("cannot disable Events while %s exists; automatic Events removal is not supported", path)
			}
		}
	}
	for _, app := range projectlayout.RuntimeApps(".", p.config) {
		if err := validateLegacyEventOwnerSource(app); err != nil {
			return err
		}
		if appRenderComponents(p.config, app).Events {
			continue
		}
		for _, path := range []string{
			filepath.Join(projectlayout.WireDir(".", app), "inject_subscribers_app.go"),
			filepath.Join(projectlayout.AppDir(".", app), "event_commands.go"),
		} {
			exists, err := renderPathExists(path)
			if err != nil {
				return err
			}
			if exists {
				return fmt.Errorf("cannot disable Events for App %q while %s exists; automatic Events removal is not supported", app.Name, path)
			}
		}
		for _, path := range legacyEventSubscriberOwnerPaths(app) {
			exists, err := renderPathExists(path)
			if err != nil {
				return err
			}
			if exists {
				return fmt.Errorf("cannot disable Events for App %q while legacy subscriber owner %s exists; migrate or reconcile that App-owned file first", app.Name, path)
			}
		}
		if legacyEventPipelineField(app) {
			path := filepath.Join(projectlayout.AppDir(".", app), "commands.go")
			return fmt.Errorf("cannot disable Events for App %q while %s registers TestEventPipelineCmd; automatic Events removal is not supported", app.Name, path)
		}
		if legacyEventPipelineProvider(app) {
			path := filepath.Join(projectlayout.WireDir(".", app), "inject_cmd_app.go")
			return fmt.Errorf("cannot disable Events for App %q while %s provides TestEventPipelineCmd; automatic Events removal is not supported", app.Name, path)
		}
		if legacyEventMakeCommandProvider(app) {
			path := filepath.Join(projectlayout.WireDir(".", app), "inject_services_app.go")
			return fmt.Errorf("cannot disable Events for App %q while %s provides Events make commands; automatic Events removal is not supported", app.Name, path)
		}
	}
	return nil
}

// validateStorageRenderTransition rejects unsupported removal states before rendering can leave stale Storage code or obscure owner references.
func (p *ProjectRenderer) validateStorageRenderTransition(projectComponents project.Components) error {
	if !projectComponents.Storage {
		for _, path := range projectStorageResiduePaths() {
			if exists, err := renderPathExists(path); err != nil {
				return err
			} else if exists {
				return fmt.Errorf("cannot disable Storage while %s exists; automatic Storage removal is not supported", path)
			}
		}
	}
	for _, app := range projectlayout.RuntimeApps(".", p.config) {
		if appRenderComponents(p.config, app).Storage {
			continue
		}
		path := filepath.Join(projectlayout.WireDir(".", app), "app.go")
		exists, err := appStorageSurfaceExists(path)
		if err != nil {
			return err
		}
		if exists {
			return fmt.Errorf("cannot disable Storage for App %q while %s exposes the generated Storage API; automatic Storage removal is not supported", app.Name, path)
		}
	}
	return nil
}

// validateJobsRenderTransition rejects unsupported removal states before rendering can strand Jobs source or App-owned providers.
func (p *ProjectRenderer) validateJobsRenderTransition(projectComponents project.Components) error {
	if !projectComponents.Jobs {
		path, exists, err := projectJobsRemovalResiduePath()
		if err != nil {
			return err
		}
		if exists {
			return fmt.Errorf("cannot disable Jobs while %s exists; automatic Jobs removal is not supported", path)
		}
	}
	for _, app := range projectlayout.RuntimeApps(".", p.config) {
		if appRenderComponents(p.config, app).Jobs {
			continue
		}
		path, exists, err := appJobsRemovalResiduePath(app)
		if err != nil {
			return err
		}
		if exists {
			return fmt.Errorf("cannot disable Jobs for App %q while %s contains generated Jobs accessors or wiring; automatic Jobs removal is not supported", app.Name, path)
		}
	}
	return nil
}

// legacyJobsFrameworkPaths lists obsolete generated Jobs files retained only for cleanup compatibility.
func legacyJobsFrameworkPaths() []string {
	return []string{
		filepath.Join("internal", "jobs", "devconsole.go"),
		filepath.Join("internal", "jobs", "queue_registration.go"),
	}
}

// projectJobsRemovalResiduePath centralizes the ownership boundary so renders and App removal reject the same residue.
func projectJobsRemovalResiduePath() (string, bool, error) {
	for _, path := range projectJobsResiduePaths() {
		exists, residuePath, err := jobsRemovalResidueExists(path)
		if err != nil {
			return "", false, err
		}
		if exists {
			return residuePath, true, nil
		}
	}
	return "", false, nil
}

// jobsRemovalResidueExists treats empty shells as harmless because earlier renderers can leave component directories behind.
func jobsRemovalResidueExists(path string) (bool, string, error) {
	info, err := os.Stat(path)
	if os.IsNotExist(err) {
		return false, "", nil
	}
	if err != nil {
		return false, "", fmt.Errorf("inspect component transition path %s: %w", path, err)
	}
	if !info.IsDir() {
		return true, path, nil
	}

	legacyFramework := make(map[string]struct{}, len(legacyJobsFrameworkPaths()))
	for _, frameworkPath := range legacyJobsFrameworkPaths() {
		legacyFramework[filepath.Clean(frameworkPath)] = struct{}{}
	}
	residuePath := ""
	err = filepath.WalkDir(path, func(candidate string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			return nil
		}
		if _, frameworkOwned := legacyFramework[filepath.Clean(candidate)]; frameworkOwned {
			return nil
		}
		residuePath = candidate
		return fs.SkipAll
	})
	if err != nil {
		return false, "", fmt.Errorf("inspect Jobs transition directory %s: %w", path, err)
	}
	return residuePath != "", residuePath, nil
}

// projectJobsResiduePaths stays explicit so local Queue runtime data is never mistaken for project-owned Jobs source.
func projectJobsResiduePaths() []string {
	return []string{
		filepath.Join("internal", "jobs"),
		filepath.Join("internal", "queues"),
		filepath.Join("internal", "makecmd", "make_job_cmd.go"),
		filepath.Join("internal", "makecmd", "make_job_cmd_test.go"),
		filepath.Join("internal", "makecmd", "make_queue_cmd.go"),
		filepath.Join("internal", "makecmd", "make_queue_cmd_test.go"),
		filepath.Join("internal", "makecmd", "job.tmpl"),
		filepath.Join("internal", "observability", "queue_observer.go"),
		filepath.Join("internal", "observability", "queue_observer_test.go"),
		filepath.Join("containers", "observability", "grafana", "dashboards", "queue-overview.json"),
	}
}

// appJobsResiduePaths lists generated and owner-controlled Jobs injectors for one App.
func appJobsResiduePaths(app project.App) []string {
	app = projectlayout.NormalizeApp(app)
	paths := []string{
		filepath.Join(projectlayout.WireDir(".", app), "inject_jobs.go"),
		filepath.Join(projectlayout.WireDir(".", app), "inject_jobs_app.go"),
	}
	if app.Name == project.DefaultAppName {
		paths = append(paths, filepath.Join("wire", "inject_jobs_app.go"))
	}
	return paths
}

// appJobsRemovalResiduePath finds the first App-owned Jobs accessor or injector that prevents safe component removal.
func appJobsRemovalResiduePath(app project.App) (string, bool, error) {
	appPath := filepath.Join(projectlayout.WireDir(".", app), "app.go")
	exists, err := appJobsSurfaceExists(appPath)
	if err != nil {
		return "", false, err
	}
	if exists {
		return appPath, true, nil
	}
	for _, path := range appJobsResiduePaths(app) {
		exists, err := renderPathExists(path)
		if err != nil {
			return "", false, err
		}
		if exists {
			return path, true, nil
		}
	}
	return "", false, nil
}

// appJobsSurfaceExists detects Queue accessors from receiver syntax without matching comments, strings, fields, or free functions.
func appJobsSurfaceExists(path string) (bool, error) {
	file, exists, err := parsedRenderGoFile(path)
	if err != nil {
		return false, fmt.Errorf("parse Jobs transition path %s: %w", path, err)
	}
	if !exists {
		return false, nil
	}
	for _, declaration := range file.Decls {
		function, ok := declaration.(*ast.FuncDecl)
		if !ok || function.Name == nil || !receiverListNamesType(function.Recv, "App") {
			continue
		}
		if function.Name.Name == "Queue" || function.Name.Name == "Queues" {
			return true, nil
		}
	}
	return false, nil
}

// receiverListNamesType recognizes pointer and generic receiver forms for one declared type.
func receiverListNamesType(receivers *ast.FieldList, want string) bool {
	if receivers == nil || len(receivers.List) != 1 {
		return false
	}
	return receiverExpressionNamesType(receivers.List[0].Type, want)
}

// receiverExpressionNamesType unwraps receiver syntax without relying on source text.
func receiverExpressionNamesType(expression ast.Expr, want string) bool {
	switch value := expression.(type) {
	case *ast.Ident:
		return value.Name == want
	case *ast.StarExpr:
		return receiverExpressionNamesType(value.X, want)
	case *ast.IndexExpr:
		return receiverExpressionNamesType(value.X, want)
	case *ast.IndexListExpr:
		return receiverExpressionNamesType(value.X, want)
	default:
		return false
	}
}

// projectStorageResiduePaths lists generated artifacts that prove an existing project still owns a Storage surface.
func projectStorageResiduePaths() []string {
	return []string{
		filepath.Join("internal", "storages"),
		filepath.Join("internal", "observability", "storage_observer.go"),
		filepath.Join("internal", "observability", "storage_observer_test.go"),
		filepath.Join("containers", "observability", "grafana", "dashboards", "storage-overview.json"),
	}
}

// appStorageSurfaceExists detects the generated App accessor without treating comments or unrelated owner files as removal proof.
func appStorageSurfaceExists(path string) (bool, error) {
	file, exists, err := parsedRenderGoFile(path)
	if err != nil {
		return false, fmt.Errorf("parse Storage transition path %s: %w", path, err)
	}
	if !exists {
		return false, nil
	}
	for _, declaration := range file.Decls {
		function, ok := declaration.(*ast.FuncDecl)
		if !ok || function.Recv == nil || function.Name == nil || function.Name.Name != "Storage" {
			continue
		}
		return true, nil
	}
	return false, nil
}

// projectEventsResiduePaths lists component-owned artifacts that a disabled render cannot safely remove or leave active.
func projectEventsResiduePaths() []string {
	return []string{
		filepath.Join("internal", "events"),
		filepath.Join("internal", "makecmd", "make_event_cmd.go"),
		filepath.Join("internal", "makecmd", "make_event_cmd_test.go"),
		filepath.Join("internal", "makecmd", "make_subscriber_cmd.go"),
		filepath.Join("internal", "makecmd", "make_subscriber_cmd_test.go"),
		filepath.Join("internal", "makecmd", "event.tmpl"),
		filepath.Join("internal", "makecmd", "subscriber.tmpl"),
		filepath.Join("internal", "observability", "event_observer.go"),
		filepath.Join("internal", "cmd", "test_event_pipeline_cmd.go"),
		filepath.Join("containers", "observability", "grafana", "dashboards", "events-overview.json"),
	}
}

// validateLegacyEventOwnerSource ensures compatibility flags cannot silently misclassify malformed owner code.
func validateLegacyEventOwnerSource(app project.App) error {
	for _, path := range []string{
		filepath.Join(projectlayout.AppDir(".", app), "commands.go"),
		filepath.Join(projectlayout.WireDir(".", app), "inject_cmd_app.go"),
	} {
		if _, _, err := parsedRenderGoFile(path); err != nil {
			return fmt.Errorf("parse Events compatibility owner %s: %w", path, err)
		}
	}
	return validateLegacyAppServiceInjectorOwnership(app)
}

// validateLegacyAppServiceInjectorOwnership rejects obsolete framework providers that cannot be removed without interpreting owner intent.
func validateLegacyAppServiceInjectorOwnership(app project.App) error {
	path := filepath.Join(projectlayout.WireDir(".", app), "inject_services_app.go")
	file, exists, err := parsedRenderGoFile(path)
	if err != nil {
		return fmt.Errorf("parse Events compatibility owner %s: %w", path, err)
	}
	if !exists || !legacyAppServiceInjectorRequiresManualMigration(file) {
		return nil
	}
	return fmt.Errorf("cannot automatically migrate legacy Events/Redis providers in App-owned %s; reconcile provideSharedRedisClient or the Redis-backed events.NewBus provider manually so custom providers remain intact", path)
}

// legacyAppServiceInjectorRequiresManualMigration identifies executable legacy providers without matching comments or string literals.
func legacyAppServiceInjectorRequiresManualMigration(file *ast.File) bool {
	if file == nil {
		return false
	}
	found := false
	ast.Inspect(file, func(node ast.Node) bool {
		switch value := node.(type) {
		case *ast.FuncDecl:
			if value.Name != nil && value.Name.Name == "provideSharedRedisClient" {
				found = true
				return false
			}
		case *ast.CallExpr:
			if !selectorExpressionMatches(value.Fun, "events", "NewBus") {
				return true
			}
			for _, argument := range value.Args {
				identifier, ok := argument.(*ast.Ident)
				if ok && identifier.Name == "redisClient" {
					found = true
					return false
				}
			}
		}
		return !found
	})
	return found
}

// legacyEventMakeCommandProvider reports whether an owner service set still references Events-only make commands.
func legacyEventMakeCommandProvider(app project.App) bool {
	file, exists, err := parsedRenderGoFile(filepath.Join(projectlayout.WireDir(".", app), "inject_services_app.go"))
	if err != nil || !exists {
		return false
	}
	return astFileContainsSelector(file, "makecmd", "NewEventCmd", "NewSubscriberCmd")
}

// astFileContainsSelector reports whether parsed owner code references any requested qualified selector.
func astFileContainsSelector(file *ast.File, packageName string, selectorNames ...string) bool {
	if file == nil {
		return false
	}
	wanted := make(map[string]struct{}, len(selectorNames))
	for _, selectorName := range selectorNames {
		wanted[selectorName] = struct{}{}
	}
	found := false
	ast.Inspect(file, func(node ast.Node) bool {
		expression, ok := node.(ast.Expr)
		if !ok {
			return true
		}
		for selectorName := range wanted {
			if selectorExpressionMatches(expression, packageName, selectorName) {
				found = true
				return false
			}
		}
		return !found
	})
	return found
}

// renderPathExists reports whether a generated or App-owned transition path remains without masking filesystem errors.
func renderPathExists(path string) (bool, error) {
	_, err := os.Stat(path)
	if err == nil {
		return true, nil
	}
	if os.IsNotExist(err) {
		return false, nil
	}
	return false, fmt.Errorf("inspect component transition path %s: %w", path, err)
}

// legacyEventPipelineField reports whether an owner Commands struct still carries the pre-component Events command field.
func legacyEventPipelineField(app project.App) bool {
	file, exists, err := parsedRenderGoFile(filepath.Join(projectlayout.AppDir(".", app), "commands.go"))
	if err != nil || !exists {
		return false
	}
	for _, declaration := range file.Decls {
		general, ok := declaration.(*ast.GenDecl)
		if !ok || general.Tok != token.TYPE {
			continue
		}
		for _, specification := range general.Specs {
			typeSpec, ok := specification.(*ast.TypeSpec)
			if !ok || typeSpec.Name.Name != "Commands" {
				continue
			}
			commands, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}
			for _, field := range commands.Fields.List {
				if selectorExpressionMatches(field.Type, "cmd", "TestEventPipelineCmd") {
					return true
				}
			}
		}
	}
	return false
}

// legacyEventPipelineProvider reports whether an owner command Wire set already supplies the pre-component Events command.
func legacyEventPipelineProvider(app project.App) bool {
	file, exists, err := parsedRenderGoFile(filepath.Join(projectlayout.WireDir(".", app), "inject_cmd_app.go"))
	if err != nil || !exists {
		return false
	}
	for _, declaration := range file.Decls {
		general, ok := declaration.(*ast.GenDecl)
		if !ok || general.Tok != token.VAR {
			continue
		}
		for _, specification := range general.Specs {
			valueSpec, ok := specification.(*ast.ValueSpec)
			if !ok || !astIdentifierListContains(valueSpec.Names, "appCommandSet") {
				continue
			}
			found := false
			for _, value := range valueSpec.Values {
				ast.Inspect(value, func(node ast.Node) bool {
					if expression, ok := node.(ast.Expr); ok && selectorExpressionMatches(expression, "cmd", "NewTestEventPipelineCmd") {
						found = true
						return false
					}
					return !found
				})
				if found {
					return true
				}
			}
		}
	}
	return false
}

// parsedRenderGoFile parses existing owner code so compatibility flags cannot be triggered by comments or unrelated text.
func parsedRenderGoFile(path string) (*ast.File, bool, error) {
	source, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, false, nil
		}
		return nil, true, err
	}
	file, err := parser.ParseFile(token.NewFileSet(), path, source, 0)
	if err != nil {
		return nil, true, err
	}
	return file, true, nil
}

// selectorExpressionMatches recognizes one qualified selector, including pointer-wrapped field types.
func selectorExpressionMatches(expression ast.Expr, packageName string, selectorName string) bool {
	if pointer, ok := expression.(*ast.StarExpr); ok {
		expression = pointer.X
	}
	selector, ok := expression.(*ast.SelectorExpr)
	if !ok || selector.Sel.Name != selectorName {
		return false
	}
	identifier, ok := selector.X.(*ast.Ident)
	return ok && identifier.Name == packageName
}

// astIdentifierListContains reports whether a declaration names the requested variable.
func astIdentifierListContains(identifiers []*ast.Ident, want string) bool {
	for _, identifier := range identifiers {
		if identifier.Name == want {
			return true
		}
	}
	return false
}
