package forj

import (
	"path/filepath"
	"strings"
	"testing"

	"github.com/goforj/goforj/project"
)

// TestNamedAppCacheTransitionFollowsProjectLocalImports verifies provider dependencies cannot hide behind shared package boundaries.
func TestNamedAppCacheTransitionFollowsProjectLocalImports(t *testing.T) {
	usePrimitiveRendererRoot(t)
	worker := project.DefaultNamedApp("worker")
	config := &project.Config{
		GoModuleName: "example.test/cache-graph",
		Render:       project.RenderConfig{Components: project.Components{CLI: true, Cache: true}},
		Apps: map[string]project.AppConfig{
			worker.Name: {Components: project.Components{CLI: true}},
		},
	}
	writePrimitiveRendererFile(t, filepath.Join(worker.WireDir, "owner.go"), `package wire

import "example.test/cache-graph/internal/workers"

var workerService = workers.NewService
`)
	writePrimitiveRendererFile(t, filepath.Join("internal", "workers", "service.go"), `package workers

import "example.test/cache-graph/internal/platform"

func NewService(dependency *platform.Dependency) *Service { return &Service{} }

type Service struct{}
`)
	cacheOwnerPath := filepath.Join("internal", "platform", "dependency.go")
	writePrimitiveRendererFile(t, cacheOwnerPath, "package platform\n\nimport `example.test/cache-graph/internal/caches`\n\ntype Dependency struct { Manager *caches.Manager }\n")

	err := projectRendererForTest(t, config).validateCacheRenderTransition(project.ProjectComponents(config))
	if err == nil || !strings.Contains(err.Error(), cacheOwnerPath) {
		t.Fatalf("transitive Cache owner error = %v, want %s", err, cacheOwnerPath)
	}
}

// TestNamedAppCacheTransitionIgnoresOtherAppGraph verifies project Cache support does not make every App own every Cache consumer.
func TestNamedAppCacheTransitionIgnoresOtherAppGraph(t *testing.T) {
	usePrimitiveRendererRoot(t)
	worker := project.DefaultNamedApp("worker")
	reporting := project.DefaultNamedApp("reporting")
	config := &project.Config{
		GoModuleName: "example.test/cache-graph",
		Render:       project.RenderConfig{Components: project.Components{CLI: true, Cache: true}},
		Apps: map[string]project.AppConfig{
			worker.Name:    {Components: project.Components{CLI: true}},
			reporting.Name: {Components: project.Components{CLI: true, Cache: true}},
		},
	}
	writePrimitiveRendererFile(t, filepath.Join(worker.WireDir, "owner.go"), `package wire

import "example.test/cache-graph/internal/workers"

var workerService = workers.NewService
`)
	writePrimitiveRendererFile(t, filepath.Join(worker.WireDir, "wire_gen.go"), `// Code generated by Wire. DO NOT EDIT.

package wire

import "example.test/cache-graph/internal/caches"

var generatedManager *caches.Manager
`)
	writePrimitiveRendererFile(t, filepath.Join("internal", "workers", "service.go"), `package workers

type Service struct{}

func NewService() *Service { return &Service{} }
`)
	writePrimitiveRendererFile(t, filepath.Join(reporting.WireDir, "owner.go"), `package wire

import "example.test/cache-graph/internal/reports"

var reportService = reports.NewService
`)
	writePrimitiveRendererFile(t, filepath.Join("internal", "reports", "service.go"), `package reports

import "example.test/cache-graph/internal/caches"

func NewService(manager *caches.Manager) *Service { return &Service{} }

type Service struct{}
`)

	if err := projectRendererForTest(t, config).validateCacheRenderTransition(project.ProjectComponents(config)); err != nil {
		t.Fatalf("disable Cache for unrelated App graph: %v", err)
	}
}

// TestNamedAppCacheTransitionFollowsImportedSiblingApp verifies ownership pruning never hides an explicit cross-App dependency.
func TestNamedAppCacheTransitionFollowsImportedSiblingApp(t *testing.T) {
	usePrimitiveRendererRoot(t)
	worker := project.DefaultNamedApp("worker")
	reporting := project.DefaultNamedApp("reporting")
	config := &project.Config{
		GoModuleName: "example.test/cache-graph",
		Render:       project.RenderConfig{Components: project.Components{CLI: true, Cache: true}},
		Apps: map[string]project.AppConfig{
			worker.Name:    {Components: project.Components{CLI: true}},
			reporting.Name: {Components: project.Components{CLI: true, Cache: true}},
		},
	}
	writePrimitiveRendererFile(t, filepath.Join(worker.WireDir, "owner.go"), `package wire

import reporting "example.test/cache-graph/app/reporting"

var workerService = reporting.NewService
`)
	cacheOwnerPath := filepath.Join(reporting.AppDir, "service.go")
	writePrimitiveRendererFile(t, cacheOwnerPath, `package reportingapp

import "example.test/cache-graph/internal/caches"

func NewService(manager *caches.Manager) *Service { return &Service{} }

type Service struct{}
`)

	err := projectRendererForTest(t, config).validateCacheRenderTransition(project.ProjectComponents(config))
	if err == nil || !strings.Contains(err.Error(), cacheOwnerPath) {
		t.Fatalf("cross-App Cache owner error = %v, want %s", err, cacheOwnerPath)
	}
}
