package forj

import (
	"go/ast"
	"path/filepath"
	"strings"

	"github.com/goforj/goforj/internal/projectlayout"
	"github.com/goforj/goforj/project"
)

// cacheOwnerCodeDependency finds owner source that would retain a generated Cache dependency after the prospective render.
func (p *ProjectRenderer) cacheOwnerCodeDependency(components project.Components, disabledApps []project.App, ignoredApps []project.App) (string, error) {
	frameworkPaths := p.cacheReconciledGoPaths(components)
	if !components.Cache {
		search := p.cacheOwnerDependencySearch(ignoredApps, frameworkPaths)
		return search.find(".")
	}
	allApps := projectlayout.RuntimeApps(p.workspace.discoveryRoot(), p.config)
	for _, app := range disabledApps {
		otherApps := make([]project.App, 0, len(allApps)-1)
		for _, candidate := range allApps {
			if candidate.Name != app.Name {
				otherApps = append(otherApps, candidate)
			}
		}
		search := p.cacheOwnerDependencySearch(otherApps, frameworkPaths)
		for _, root := range cacheTransitionAppRoots([]project.App{app}) {
			path, err := search.find(root)
			if err != nil || path != "" {
				return path, err
			}
		}
	}
	return "", nil
}

// cacheTransitionAppRoots returns the source ownership roots removed with one or more Apps.
func cacheTransitionAppRoots(apps []project.App) []string {
	roots := make([]string, 0, len(apps)*2)
	for _, app := range apps {
		roots = append(roots, projectlayout.AppDir(".", app), projectlayout.CommandDir(".", app))
	}
	return roots
}

// cacheReconciledGoPaths lists Cache-aware source that the prospective renderer refreshes before compilation.
func (p *ProjectRenderer) cacheReconciledGoPaths(components project.Components) map[string]bool {
	paths := map[string]bool{
		filepath.Join("internal", "runtime", "about.go"):     true,
		filepath.Join("internal", "runtime", "apps.go"):      true,
		filepath.Join("internal", "runtime", "apps_test.go"): true,
		filepath.Join("internal", "runtime", "discovery.go"): true,
	}
	if components.WebAPI || components.WebUI {
		paths[filepath.Join("internal", "http", "lighthouse.go")] = true
	}
	if components.Jobs {
		for _, name := range []string{"benchmark_run_cmd.go", "lighthouse.go", "lighthouse_benchmark.go"} {
			paths[filepath.Join("internal", "jobs", name)] = true
		}
	}
	if components.Metrics {
		paths[filepath.Join("internal", "metrics", "manager.go")] = true
	}
	for _, artifact := range cacheGeneratedCleanupArtifacts() {
		paths[filepath.Clean(artifact.path)] = true
	}
	for _, app := range projectlayout.RuntimeApps(p.workspace.discoveryRoot(), p.config) {
		for _, mapping := range p.appFrameworkMappings(app) {
			paths[filepath.Clean(mapping.dest)] = true
		}
	}
	return paths
}

// cacheTransitionSkippedDirectory excludes dependencies and runtime data that cannot contain project-owned Go source.
func cacheTransitionSkippedDirectory(name string) bool {
	switch name {
	case ".git", ".idea", ".vscode", "bin", "node_modules", "vendor", "_data":
		return true
	default:
		return false
	}
}

// cacheTransitionGeneratedGoSource recognizes framework output that has its own generated ownership marker.
func cacheTransitionGeneratedGoSource(source []byte) bool {
	text := string(source)
	return strings.Contains(text, "// Code generated by GoForj CLI. DO NOT EDIT.") ||
		strings.Contains(text, "// Code generated by forj generate --") ||
		strings.Contains(text, "// Code generated by Wire. DO NOT EDIT.")
}

// cacheGoFileDependsOnGeneratedAPI recognizes imports and App Wire accessor calls that disappear when Cache is disabled.
func cacheGoFileDependsOnGeneratedAPI(path string, file *ast.File) bool {
	importsAppWire := false
	for _, imported := range file.Imports {
		importPath, ok := cacheImportPath(imported.Path.Value)
		if !ok {
			continue
		}
		if strings.HasSuffix(importPath, "/internal/caches") {
			return true
		}
		importsAppWire = importsAppWire || strings.HasSuffix(importPath, "/app/wire") ||
			(strings.Contains(importPath, "/app/") && strings.HasSuffix(importPath, "/wire"))
	}
	logical := filepath.ToSlash(path)
	insideAppWire := strings.HasPrefix(logical, "app/wire/") ||
		(strings.HasPrefix(logical, "app/") && strings.Contains(logical, "/wire/"))
	if !importsAppWire && !insideAppWire {
		return false
	}
	depends := false
	ast.Inspect(file, func(node ast.Node) bool {
		call, ok := node.(*ast.CallExpr)
		if !ok {
			return true
		}
		selector, ok := call.Fun.(*ast.SelectorExpr)
		if ok && (selector.Sel.Name == "Cache" || selector.Sel.Name == "Caches") {
			depends = true
			return false
		}
		return true
	})
	return depends
}
