package forj

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// redisShellGeneratedCleanupArtifact describes one framework-owned Redis shell file.
type redisShellGeneratedCleanupArtifact struct {
	path   string
	marker string
}

// redisShellGeneratedCleanupArtifacts returns files that become stale when no App owns a Redis-capable resource.
func redisShellGeneratedCleanupArtifacts() []redisShellGeneratedCleanupArtifact {
	const generatedMarker = "// Code generated by GoForj CLI. DO NOT EDIT."
	return []redisShellGeneratedCleanupArtifact{
		{path: filepath.Join("internal", "cmd", "redis_shell_cmd.go"), marker: generatedMarker},
		{path: filepath.Join("internal", "cmd", "redis_shell_cmd_test.go"), marker: generatedMarker},
	}
}

// validateRedisShellGeneratedCleanupArtifacts prevents a capability transition from deleting owner code.
func (w projectRenderWorkspace) validateRedisShellGeneratedCleanupArtifacts() error {
	for _, artifact := range redisShellGeneratedCleanupArtifacts() {
		contents, err := w.readFile(artifact.path)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return fmt.Errorf("inspect generated Redis shell artifact %s: %w", artifact.path, err)
		}
		if !strings.Contains(string(contents), artifact.marker) {
			return fmt.Errorf("Redis shell is disabled but %s does not carry the generated ownership marker; preserve or move it before rendering", artifact.path)
		}
	}
	return nil
}

// cleanupDisabledRedisShellGeneratedFiles removes only proven framework-owned Redis shell artifacts.
func (w projectRenderWorkspace) cleanupDisabledRedisShellGeneratedFiles() error {
	if err := w.validateRedisShellGeneratedCleanupArtifacts(); err != nil {
		return err
	}
	for _, artifact := range redisShellGeneratedCleanupArtifacts() {
		if _, err := w.removeFileIfExists(artifact.path); err != nil {
			return err
		}
	}
	return nil
}
