// Code generated by forj generate --storage. DO NOT EDIT.
// Run: forj generate --storage
package storage

import (
	"fmt"
	"path/filepath"

	"github.com/goforj/env/v2"
	goforjstorage "github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
	"github.com/goforj/str"
)

func loadDisksFromEnv(storageScope env.Scope) (map[goforjstorage.DiskName]goforjstorage.DriverConfig, error) {
	disks := map[goforjstorage.DiskName]goforjstorage.DriverConfig{}

	defaultCfg, err := buildDiskConfig(defaultDiskName, storageScope)
	if err != nil {
		return nil, err
	}
	disks[defaultDiskName] = defaultCfg

	for _, child := range storageScope.ChildNames(storageRootKeys) {
		name := goforjstorage.DiskName(str.Of(child).TrimSpace().ToLower().String())
		cfg, err := buildDiskConfig(name, storageScope.Child(child))
		if err != nil {
			return nil, err
		}
		disks[name] = cfg
	}

	return disks, nil
}

func buildDiskConfig(name goforjstorage.DiskName, scope env.Scope) (goforjstorage.DriverConfig, error) {
	driver := str.Of(scope.Get("DRIVER", driverLocal)).TrimSpace().ToLower().String()
	if driver == "" {
		driver = driverLocal
	}

	localRoot := filepath.Join("storage", "app", "private")
	if name != defaultDiskName {
		localRoot = filepath.Join("storage", "app", string(name))
	}

	switch driver {
	case driverLocal:
		return localstorage.Config{
			Root:   scope.Get("ROOT", localRoot),
			Prefix: scope.Get("PREFIX", ""),
		}, nil
	default:
		return nil, fmt.Errorf("storage: unsupported driver %q", driver)
	}
}
