// Code generated by forj generate --storage. DO NOT EDIT.
// Run: forj generate --storage
//
// The default disk is exposed by Manager.Default().
// This file contains named storage disk accessors generated from
// STORAGE_<NAME>_<KEY> environment variables.
package storage
