// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/goforj/goforj/internal/cmd"
	"github.com/goforj/goforj/internal/goforj"
	"github.com/goforj/goforj/internal/logger"
)

// Injectors from wire.go:

// InitializeApplication initializes the application with all its dependencies.
func InitializeApplication() (App, error) {
	appLogger := logger.ProvideAppLogger()
	makeMigrationCmd := goforj.NewMakeMigrationCmd(appLogger)
	makeControllerCmd := goforj.NewMakeControllerCmd(appLogger)
	makeCommandCmd := goforj.NewMakeCommandCmd(appLogger)
	newProjectCmd := goforj.NewNewProjectCmd(appLogger)
	devCmd := goforj.NewDevCmd(appLogger)
	buildBinaryCmd := goforj.NewBuildBinaryCmd(appLogger)
	projectRenderer := goforj.NewProjectRenderer(appLogger)
	renderCmd := goforj.NewCmd(appLogger, projectRenderer)
	runCmd := goforj.NewRunCmd(appLogger)
	rootCmd := goforj.NewRootCmd(makeMigrationCmd, makeControllerCmd, makeCommandCmd, newProjectCmd, devCmd, buildBinaryCmd, renderCmd, runCmd)
	helloWorldCmd := cmd.NewHelloWorldCmd(appLogger)
	cmdRootCmd := cmd.NewRootCmd(rootCmd, helloWorldCmd)
	app := NewApplication(appLogger, cmdRootCmd)
	return app, nil
}
