// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/goforj/goforj/internal/cmd"
	"github.com/goforj/goforj/internal/forj"
	"github.com/goforj/goforj/internal/launcher"
	"github.com/goforj/goforj/internal/logger"
)

// Injectors from wire.go:

// InitializeApplication initializes the application with all its dependencies.
func InitializeApplication() (App, error) {
	appLogger := logger.ProvideAppLogger()
	projectRenderer := forj.NewProjectRenderer(appLogger)
	projectAuthoringCommands := forj.NewProjectAuthoringCommands(appLogger, projectRenderer)
	runner := forj.ProvideAPIIndexRunner()
	buildCommands := forj.NewBuildCommands(appLogger, runner)
	environment := launcher.Provide()
	runtimeCommands := forj.NewRuntimeCommands(appLogger, runner, environment)
	atlasCommands := forj.NewAtlasCommands()
	testCommands := forj.NewTestCommands(appLogger)
	benchmarkCommands := forj.NewBenchmarkCommands(appLogger)
	scenarioCommands := forj.NewScenarioCommands(appLogger)
	backupCommands := forj.NewBackupCommands()
	rootCmd := forj.NewRootCmd(projectAuthoringCommands, buildCommands, runtimeCommands, atlasCommands, testCommands, benchmarkCommands, scenarioCommands, backupCommands)
	helloWorldCmd := cmd.NewHelloWorldCmd(appLogger)
	cmdRootCmd := cmd.NewRootCmd(rootCmd, helloWorldCmd)
	app := NewApplication(appLogger, cmdRootCmd)
	return app, nil
}
