// Code generated by forj generate --cache. DO NOT EDIT.
// Run: forj generate --cache
//
// These cache manager accessors are derived from the current .env file
// and environment variables available when generation ran.
// Named accessors are generated from CACHE_<NAME>_<KEY> environment variables.
package caches

import (
	"github.com/goforj/cache"
	"github.com/goforj/str/v2"
)

// Default returns the default cache instance derived from CACHE_* configuration.
func (m *Manager) Default() *cache.Cache {
	return m.defaultStore
}

// Sessions returns the "sessions" cache instance when configured.
func (m *Manager) Sessions() *cache.Cache {
	return m.sessions
}

// Names returns the generated cache names derived from CACHE_* configuration.
func (m *Manager) Names() []string {
	return []string{"default"}
}

// Named returns the generated cache instance for a configured cache name.
func (m *Manager) Named(name string) *cache.Cache {
	switch str.Of(name).Trim().ToLower().String() {
	case "", "default":
		return m.defaultStore
	default:
		return nil
	}
}
