// Code generated by forj generate --cache. DO NOT EDIT.
// Run: forj generate --cache
package caches

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/goforj/cache"
	"github.com/goforj/cache/cachecore"
	"github.com/goforj/env/v2"
	"github.com/goforj/str"
)

const defaultCacheName = "default"

const (
	driverFile      = "file"
	driverMemory    = "memory"
	driverMemcached = "memcached"
	driverMySQL     = "mysql"
	driverNATS      = "nats"
	driverNull      = "null"
	driverDynamo    = "dynamodb"
	driverPostgres  = "postgres"
	driverRedis     = "redis"
	driverSQLite    = "sqlite"
)

var cacheRootKeys = []string{
	"DRIVER",
	"DEFAULT_TTL_SECONDS",
	"PREFIX",
	"MEMORY_CLEANUP_SECONDS",
	"FILE_DIR",
	"ADDR",
	"ADDRESSES",
	"USERNAME",
	"PASSWORD",
	"DB",
	"DSN",
	"TABLE",
	"ENDPOINT",
	"REGION",
	"TLS",
	"INSECURE_SKIP_VERIFY",
	"URL",
	"BUCKET",
	"BUCKET_TTL",
	"BUCKET_TTL_SECONDS",
	"DESCRIPTION",
	"HISTORY",
	"MAX_BYTES",
	"MAX_VALUE_SIZE",
	"REPLICAS",
	"STORAGE",
	"COMPRESSED",
	"COMPRESSION",
	"MAX_VALUE_BYTES",
	"ENCRYPTION_KEY",
}

// Manager owns the cache instances selected by this generated driver manifest.
type Manager struct {
	defaultStore *cache.Cache
	sessions     *cache.Cache
}

// ReadinessCheck names a generated cache probe for framework health reporting.
type ReadinessCheck struct {
	Name  string
	Check func(context.Context) error
}

// NewManager builds cache instances from the environment contract captured by this generated artifact.
func NewManager() (*Manager, error) {
	return newManagerFromEnv(env.WithPrefix("CACHE"))
}

// ReadinessChecks exposes one probe per generated cache so health reflects every configured store.
func (m *Manager) ReadinessChecks() []ReadinessCheck {
	return []ReadinessCheck{
		{
			Name: "cache_default",
			Check: func(ctx context.Context) error {
				return cacheReadinessCheck(ctx, m.defaultStore)
			},
		},
	}
}

// newManagerFromEnv constructs only the cache stores captured when this artifact was generated.
func newManagerFromEnv(cacheScope env.Scope) (*Manager, error) {
	defaultStore, err := buildStore(defaultCacheName, cacheScope)
	if err != nil {
		return nil, err
	}
	return &Manager{defaultStore: defaultStore}, nil
}

// buildStore keeps driver defaults and shared cache behavior consistent across generated stores.
func buildStore(name string, scope env.Scope) (*cache.Cache, error) {
	driver := str.Of(scope.Get("DRIVER", driverMemory)).TrimSpace().ToLower().String()
	if driver == "" {
		driver = driverMemory
	}

	baseConfig := cachecore.BaseConfig{
		DefaultTTL:    cacheDefaultTTL(scope),
		Prefix:        cachePrefix(scope),
		Compression:   cacheCompression(scope),
		MaxValueBytes: scope.GetInt("MAX_VALUE_BYTES", "0"),
		EncryptionKey: cacheEncryptionKey(scope),
	}
	if err := cachecore.ValidateBaseConfig(baseConfig); err != nil {
		return nil, fmt.Errorf("cache %q: invalid shaping configuration: %w", name, err)
	}

	switch driver {
	case driverNull:
		store := cache.NewNullStoreWithConfig(context.Background(), cache.StoreConfig{
			BaseConfig: baseConfig,
		})
		return cache.NewCacheWithTTL(store, baseConfig.DefaultTTL), nil
	case driverFile:
		store := cache.NewFileStoreWithConfig(context.Background(), cache.StoreConfig{
			BaseConfig: baseConfig,
			FileDir:    cacheFileDir(name, scope),
		})
		return cache.NewCacheWithTTL(store, baseConfig.DefaultTTL), nil
	case driverMemory:
		store := cache.NewMemoryStoreWithConfig(context.Background(), cache.StoreConfig{
			BaseConfig:            baseConfig,
			MemoryCleanupInterval: cacheMemoryCleanupInterval(scope),
		})
		return cache.NewCacheWithTTL(store, baseConfig.DefaultTTL), nil
	default:
		return nil, fmt.Errorf("cache: unsupported driver %q", driver)
	}
}

// cacheDefaultTTL preserves expiration when configuration is missing or non-positive.
func cacheDefaultTTL(scope env.Scope) time.Duration {
	seconds := scope.GetInt("DEFAULT_TTL_SECONDS", "300")
	if seconds <= 0 {
		seconds = 300
	}
	return time.Duration(seconds) * time.Second
}

// cacheMemoryCleanupInterval preserves periodic cleanup when configuration is missing or non-positive.
func cacheMemoryCleanupInterval(scope env.Scope) time.Duration {
	seconds := scope.GetInt("MEMORY_CLEANUP_SECONDS", "600")
	if seconds <= 0 {
		seconds = 600
	}
	return time.Duration(seconds) * time.Second
}

// cachePrefix keeps the default namespace stable while allowing an explicit application prefix.
func cachePrefix(scope env.Scope) string {
	value := scope.Get("PREFIX", "app")
	if value == "" {
		return "app"
	}
	return value
}

// cacheFileDir isolates named file stores when no directory is supplied explicitly.
func cacheFileDir(name string, scope env.Scope) string {
	value := strings.TrimSpace(scope.Get("FILE_DIR", ""))
	if value != "" {
		return value
	}
	base := filepath.Join(os.TempDir(), "cache-file")
	if name == "" || name == defaultCacheName {
		return base
	}
	return filepath.Join(base, name)
}

// cacheCompression preserves invalid values so manager construction can report configuration mistakes.
func cacheCompression(scope env.Scope) cachecore.CompressionCodec {
	value := str.Of(scope.Get("COMPRESSION", "none")).TrimSpace().ToLower().String()
	switch value {
	case "", "none":
		return cachecore.CompressionNone
	case "gzip":
		return cachecore.CompressionGzip
	case "snappy":
		return cachecore.CompressionSnappy
	default:
		return cachecore.CompressionCodec(value)
	}
}

// cacheEncryptionKey treats blank configuration as encryption disabled instead of an empty secret.
func cacheEncryptionKey(scope env.Scope) []byte {
	value := strings.TrimSpace(scope.Get("ENCRYPTION_KEY", ""))
	if value == "" {
		return nil
	}
	return []byte(value)
}

// cacheReadinessCheck adapts both wrapper and driver readiness contracts to one generated probe.
func cacheReadinessCheck(ctx context.Context, store *cache.Cache) error {
	if ready, ok := any(store).(interface{ Ready() error }); ok {
		return ready.Ready()
	}
	if ready, ok := any(store.Store()).(interface{ Ready(context.Context) error }); ok {
		return ready.Ready(ctx)
	}
	return nil
}
