package generate

import (
	"bytes"
	"fmt"
	"go/format"
	"path/filepath"
	"sort"
	"text/template"

	"github.com/goforj/env/v2"
	"github.com/goforj/str"
)

type dbTemplateData struct {
	HasNames bool
	Names    []dbAccessorName
}

type dbAccessorName struct {
	Method string
	Name   string
}

var dbRootKeys = []string{
	"DEFAULT",
	"DRIVER",
	"DSN",
	"HOST",
	"DATABASE",
	"USERNAME",
	"PASSWORD",
	"PORT",
	"QUERY_LOGGING",
	"MAX_IDLE_CONNECTIONS",
	"MAX_OPEN_CONNECTIONS",
	"CONN_MAX_LIFETIME_MINUTES",
	"ROOT_PASSWORD",
}

func GenerateDBFiles(projectDir string) (int, error) {
	source, err := renderDBAccessors(discoverDBConnectionNames())
	if err != nil {
		return 0, err
	}
	formatted, err := format.Source(source)
	if err != nil {
		return 0, fmt.Errorf("failed to format generated db accessors: %w", err)
	}
	changed, err := writeGeneratedSource(filepath.Join(projectDir, "internal", "dbconns", "connections_gen.go"), formatted)
	if err != nil {
		return 0, err
	}
	if changed {
		return 1, nil
	}
	return 0, nil
}

func discoverDBConnectionNames() []string {
	names := env.WithPrefix("DB").ChildNames(dbRootKeys)
	out := make([]string, 0, len(names))
	for _, name := range names {
		normalized := str.Of(name).TrimSpace().ToLower().String()
		if normalized == "" || normalized == "root" {
			continue
		}
		out = append(out, normalized)
	}
	sort.Strings(out)
	return out
}

func renderDBAccessors(names []string) ([]byte, error) {
	data := dbTemplateData{
		HasNames: false,
		Names:    make([]dbAccessorName, 0, len(names)),
	}
	for _, name := range names {
		if name == "default" {
			continue
		}
		data.HasNames = true
		data.Names = append(data.Names, dbAccessorName{
			Method: str.Of(name).Pascal().String(),
			Name:   name,
		})
	}
	var b bytes.Buffer
	tmpl, err := template.New("db-accessors").Parse(dbAccessorsSourceTemplate)
	if err != nil {
		return nil, err
	}
	if err := tmpl.Execute(&b, data); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

const dbAccessorsSourceTemplate = `// Code generated by forj generate --db. DO NOT EDIT.
// Run: forj generate --db
//
// This file contains accessors generated from DB_<NAME>_<KEY> environment variables.
// For example, DB_ANALYTICS_DRIVER will generate GetAnalytics().
package dbconns

{{- if .HasNames }}
import "gorm.io/gorm"
{{ end }}
{{ range .Names }}
// Get{{ .Method }} returns the "{{ .Name }}" connection.
func (c *Connections) Get{{ .Method }}() (*gorm.DB, error) {
	return c.get("{{ .Name }}")
}

{{ end }}`
