package generate

import (
	"bytes"
	"fmt"
	"go/format"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/goforj/env/v2"
	"github.com/goforj/str"
)

type dbTemplateData struct {
	HasNames        bool
	NeedsGormImport bool
	Names           []dbAccessorName
	Drivers         []dbDriverSpec
}

type dbAccessorName struct {
	Method string
	Name   string
}

type dbDriverSpec struct {
	Alias       string
	ImportPath  string
	SwitchCases []string
	Constructor string
	PrepareDSN  bool
}

var dbRootKeys = []string{
	"DEFAULT",
	"DRIVER",
	"DSN",
	"HOST",
	"DATABASE",
	"USERNAME",
	"PASSWORD",
	"PORT",
	"QUERY_LOGGING",
	"MAX_IDLE_CONNECTIONS",
	"MAX_OPEN_CONNECTIONS",
	"CONN_MAX_LIFETIME_MINUTES",
	"ROOT_PASSWORD",
}

func GenerateDBFiles(projectDir string) (int, error) {
	drivers, err := discoverDBDrivers()
	if err != nil {
		return 0, err
	}
	source, err := renderDBAccessors(discoverDBConnectionNames(), drivers)
	if err != nil {
		return 0, err
	}
	formatted, err := format.Source(source)
	if err != nil {
		return 0, fmt.Errorf("failed to format generated db accessors: %w", err)
	}
	changed, err := writeGeneratedSource(filepath.Join(projectDir, "internal", "database", "connections_gen.go"), formatted)
	if err != nil {
		return 0, err
	}
	if changed {
		return 1, nil
	}
	return 0, nil
}

func discoverDBConnectionNames() []string {
	names := exactScopedChildNames("DB", dbRootKeys)
	out := make([]string, 0, len(names))
	for _, name := range names {
		normalized := str.Of(name).TrimSpace().ToLower().String()
		if normalized == "" || normalized == "root" || dbHelperConnectionName(normalized) {
			continue
		}
		out = append(out, normalized)
	}
	sort.Strings(out)
	return out
}

// dbHelperConnectionName skips driver-specific helper keys such as DB_SQLITE_DATABASE.
func dbHelperConnectionName(name string) bool {
	switch strings.TrimSpace(strings.ToLower(name)) {
	case "mysql", "postgres", "postgresql", "sqlite", "sqlite3":
		return true
	default:
		return false
	}
}

func renderDBAccessors(names []string, drivers []dbDriverSpec) ([]byte, error) {
	data := dbTemplateData{
		HasNames:        false,
		NeedsGormImport: len(names) > 1 || len(drivers) > 0,
		Names:           make([]dbAccessorName, 0, len(names)),
		Drivers:         drivers,
	}
	for _, name := range names {
		if name == "default" {
			continue
		}
		data.HasNames = true
		data.Names = append(data.Names, dbAccessorName{
			Method: str.Of(name).Pascal().String(),
			Name:   name,
		})
	}
	var b bytes.Buffer
	tmpl, err := template.New("db-accessors").Parse(dbAccessorsSourceTemplate)
	if err != nil {
		return nil, err
	}
	if err := tmpl.Execute(&b, data); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

func discoverDBDrivers() ([]dbDriverSpec, error) {
	drivers := map[string]dbDriverSpec{}
	rawSupported := str.Of(env.WithPrefix("DB").Get("SUPPORTED_DRIVERS", "")).TrimSpace().ToLower().String()
	if rawSupported != "" {
		for _, part := range strings.Split(rawSupported, ",") {
			driver := str.Of(part).TrimSpace().ToLower().String()
			if driver == "" {
				continue
			}
			if !recordDBDriver(drivers, driver) {
				return nil, fmt.Errorf("DB_SUPPORTED_DRIVERS includes unsupported driver %q", driver)
			}
		}
	}
	if len(drivers) == 0 {
		recordDBDriver(drivers, str.Of(env.WithPrefix("DB").Get("DRIVER", "")).TrimSpace().ToLower().String())
		for _, name := range discoverDBConnectionNames() {
			scope := env.WithPrefix("DB").Child(str.Of(name).Snake("_").ToUpper().String())
			recordDBDriver(drivers, str.Of(scope.Get("DRIVER", "")).TrimSpace().ToLower().String())
		}
		if len(drivers) == 0 {
			recordDBDriver(drivers, "sqlite")
		}
	}
	out := make([]dbDriverSpec, 0, len(drivers))
	for _, driver := range drivers {
		out = append(out, driver)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Alias < out[j].Alias })
	return out, nil
}

func recordDBDriver(drivers map[string]dbDriverSpec, driver string) bool {
	switch driver {
	case "mysql", "mariadb":
		drivers["mysql"] = dbDriverSpec{
			Alias:       "mysql",
			ImportPath:  "gorm.io/driver/mysql",
			SwitchCases: []string{"mysql", "mariadb"},
			Constructor: `mysql.New(mysql.Config{DSN: dsn, DisableWithReturning: true})`,
		}
		return true
	case "postgres", "postgresql":
		drivers["postgres"] = dbDriverSpec{
			Alias:       "postgres",
			ImportPath:  "gorm.io/driver/postgres",
			SwitchCases: []string{"postgres", "postgresql"},
			Constructor: "postgres.Open(dsn)",
		}
		return true
	case "sqlite", "sqlite3":
		drivers["sqlite"] = dbDriverSpec{
			Alias:       "sqlite",
			ImportPath:  "github.com/glebarez/sqlite",
			SwitchCases: []string{"sqlite", "sqlite3"},
			Constructor: "sqlite.Open(dsn)",
			PrepareDSN:  true,
		}
		return true
	}
	return false
}

const dbAccessorsSourceTemplate = `// Code generated by forj generate --db. DO NOT EDIT.
// Run: forj generate --db
//
// This file contains accessors generated from DB_<NAME>_<KEY> environment variables.
// For example, DB_ANALYTICS_DRIVER will generate GetAnalytics().
package database

{{- if .NeedsGormImport }}
import (
	"context"
	"fmt"
	{{- if .Drivers }}
	{{- range .Drivers }}
	"{{ .ImportPath }}"
	{{- end }}
	{{- end }}
	"gorm.io/gorm"
)
{{ end }}
type ReadinessCheck struct {
	Name  string
	Check func(context.Context) error
}

func (c *Connections) ReadinessChecks() []ReadinessCheck {
	if c == nil {
		return nil
	}
	checks := []ReadinessCheck{
		{
			Name: "db_default",
			Check: func(ctx context.Context) error {
				return c.readinessCheck(ctx, "default")
			},
		},
{{- range .Names }}
		{
			Name: "db_{{ .Name }}",
			Check: func(ctx context.Context) error {
				return c.readinessCheck(ctx, "{{ .Name }}")
			},
		},
{{- end }}
	}
	return checks
}

func (c *Connections) readinessCheck(ctx context.Context, name string) error {
	conn, err := c.Connection(name)
	if err != nil {
		return err
	}
	sqlDB, err := conn.DB()
	if err != nil {
		return err
	}
	return sqlDB.PingContext(ctx)
}

{{- if .Drivers }}

func openDialector(driver, dsn string) (gorm.Dialector, error) {
	switch driver {
	{{- range .Drivers }}
	case {{ range $idx, $case := .SwitchCases }}{{ if $idx }}, {{ end }}"{{ $case }}"{{ end }}:
		{{- if .PrepareDSN }}
		if err := ensureSQLitePath(dsn); err != nil {
			return nil, err
		}
		{{- end }}
		return {{ .Constructor }}, nil
	{{- end }}
	default:
		return nil, fmt.Errorf("unsupported driver %q", driver)
	}
}
{{ end }}
{{ range .Names }}
// Get{{ .Method }} returns the "{{ .Name }}" connection.
func (c *Connections) Get{{ .Method }}() (*gorm.DB, error) {
	return c.get("{{ .Name }}")
}

{{ end }}`
